///////////////////////////////////////////////////////////
//  AngleDegrees.cs
//  Implementation of the Class AngleDegrees
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Measurement of angle in degrees.
	/// </summary>
	public class AngleDegrees {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.deg;
		public System.Single value;

		public AngleDegrees(){

		}

		~AngleDegrees(){

		}

		public virtual void Dispose(){

		}

	}//end AngleDegrees

}//end namespace Domain