///////////////////////////////////////////////////////////
//  DateInterval.cs
//  Implementation of the Class DateInterval
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Interval between two dates.
	/// </summary>
	public class DateInterval {

		/// <summary>
		/// End date of this interval.
		/// </summary>
		public Date end;
		/// <summary>
		/// Start date of this interval.
		/// </summary>
		public Date start;

		public DateInterval(){

		}

		~DateInterval(){

		}

		public virtual void Dispose(){

		}

	}//end DateInterval

}//end namespace Domain