///////////////////////////////////////////////////////////
//  KiloActivePower.cs
//  Implementation of the Class KiloActivePower
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Active power in kilowatts.
	/// </summary>
	public class KiloActivePower {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.k;
		public static readonly UnitSymbol unit = UnitSymbol.W;
		public Float value;

		public KiloActivePower(){

		}

		~KiloActivePower(){

		}

		public virtual void Dispose(){

		}

	}//end KiloActivePower

}//end namespace Domain