///////////////////////////////////////////////////////////
//  Money.cs
//  Implementation of the Class Money
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Amount of money.
	/// </summary>
	public class Money {

		public UnitMultiplier multiplier;
		public Currency unit;
		public Decimal value;

		public Money(){

		}

		~Money(){

		}

		public virtual void Dispose(){

		}

	}//end Money

}//end namespace Domain