///////////////////////////////////////////////////////////
//  Pressure.cs
//  Implementation of the Class Pressure
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Pressure in pascals.
	/// </summary>
	public class Pressure {

		public UnitMultiplier multiplier;
		public static readonly UnitSymbol unit = UnitSymbol.Pa;
		public Float value;

		public Pressure(){

		}

		~Pressure(){

		}

		public virtual void Dispose(){

		}

	}//end Pressure

}//end namespace Domain