///////////////////////////////////////////////////////////
//  Susceptance.cs
//  Implementation of the Class Susceptance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Imaginary part of admittance.
	/// </summary>
	public class Susceptance {

		public UnitMultiplier multiplier;
		public static readonly UnitSymbol unit = UnitSymbol.S;
		public System.Single value;

		public Susceptance(){

		}

		~Susceptance(){

		}

		public virtual void Dispose(){

		}

	}//end Susceptance

}//end namespace Domain