///////////////////////////////////////////////////////////
//  CSCtype1.cs
//  Implementation of the Class CSCtype1
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC {
	public class CSCtype1 : CSCDynamics {

		public CSCtype1(){

		}

		~CSCtype1(){

		}

		public override void Dispose(){

		}

	}//end CSCtype1

}//end namespace CSC