///////////////////////////////////////////////////////////
//  PFVArControllerType2UserDefined.cs
//  Implementation of the Class PFVArControllerType2UserDefined
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType2Dynamics;
namespace TC57CIM.IEC61970.Dynamics.UserDefinedModels {
	/// <summary>
	/// Power factor or VAr controller type 2 function block whose dynamic behaviour is
	/// described by <font color="#0f0f0f">a user-defined model.</font>
	/// </summary>
	public class PFVArControllerType2UserDefined : PFVArControllerType2Dynamics {

		/// <summary>
		/// Behaviour is based on a proprietary model as opposed to a detailed model.
		/// true = user-defined model is proprietary with behaviour mutually understood by
		/// sending and receiving applications and parameters passed as general attributes
		/// false = user-defined model is explicitly defined in terms of control blocks and
		/// their input and output signals.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean proprietary;

		public PFVArControllerType2UserDefined(){

		}

		~PFVArControllerType2UserDefined(){

		}

		public override void Dispose(){

		}

	}//end PFVArControllerType2UserDefined

}//end namespace UserDefinedModels