///////////////////////////////////////////////////////////
//  SynchronousMachineUserDefined.cs
//  Implementation of the Class SynchronousMachineUserDefined
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:24 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.SynchronousMachineDynamics;
namespace TC57CIM.IEC61970.Dynamics.UserDefinedModels {
	/// <summary>
	/// Synchronous machine whose dynamic behaviour is described by a user-defined
	/// model.
	/// </summary>
	public class SynchronousMachineUserDefined : SynchronousMachineDynamics {

		/// <summary>
		/// Behaviour is based on a proprietary model as opposed to a detailed model.
		/// true = user-defined model is proprietary with behaviour mutually understood by
		/// sending and receiving applications and parameters passed as general attributes
		/// false = user-defined model is explicitly defined in terms of control blocks and
		/// their input and output signals.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean proprietary;

		public SynchronousMachineUserDefined(){

		}

		~SynchronousMachineUserDefined(){

		}

		public override void Dispose(){

		}

	}//end SynchronousMachineUserDefined

}//end namespace UserDefinedModels