///////////////////////////////////////////////////////////
//  OperatingMechanismKind.cs
//  Implementation of the Class OperatingMechanismKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Kinds of operating mechanisms.
	/// </summary>
	public enum OperatingMechanismKind : int {

		/// <summary>
		/// Capacitor trip mechanism.
		/// </summary>
		capacitorTrip,
		/// <summary>
		/// Hydraulic mechanism.
		/// </summary>
		hydraulic,
		/// <summary>
		/// Pneudraulic mechanism.
		/// </summary>
		pneudraulic,
		/// <summary>
		/// Pneumatic mechanism.
		/// </summary>
		pneumatic,
		/// <summary>
		/// Solenoid mechanism.
		/// </summary>
		solenoid,
		/// <summary>
		/// Spring mechanism.
		/// </summary>
		spring,
		/// <summary>
		/// Spring hand-crank mechanism.
		/// </summary>
		springHandCrank,
		/// <summary>
		/// Spring hydraulic mechanism.
		/// </summary>
		springHydraulic,
		/// <summary>
		/// Spring motor mechanism.
		/// </summary>
		springMotor

	}//end OperatingMechanismKind

}//end namespace AssetInfo