///////////////////////////////////////////////////////////
//  IEC61968CIMVersion.cs
//  Implementation of the Class IEC61968CIMVersion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968 {
	/// <summary>
	/// IEC 61968 version number assigned to this UML model.
	/// </summary>
	public class IEC61968CIMVersion {

		/// <summary>
		/// (const=2016-10-31) Form is YYYY-MM-DD for example for January 5, 2009 it is
		/// 2009-01-05.
		/// </summary>
		public static readonly System.DateTime date = new System.DateTime(2022,7,4);
		/// <summary>
		/// (const=IEC61968CIM13v09) Form is IEC61968CIMXXvYY[a-z] where XX is the major
		/// CIM package version and the YY is the minor version. For example
		/// IEC61968CIM10v17a.
		/// The letter on the version number indicates the changes are due to National
		/// Committee comments.
		/// </summary>
		public static readonly string version = "IEC61968CIM13v13b";

		public IEC61968CIMVersion(){

		}

		~IEC61968CIMVersion(){

		}

		public virtual void Dispose(){

		}

	}//end IEC61968CIMVersion

}//end namespace IEC61968