///////////////////////////////////////////////////////////
//  SvSwitch.cs
//  Implementation of the Class SvSwitch
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
//  Original author: USMAMIL1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Wires;
using TC57CIM.IEC61970.Base.StateVariables;
namespace TC57CIM.IEC61970.Base.StateVariables {
	/// <summary>
	/// State variable for switch.
	/// </summary>
	public class SvSwitch : StateVariable {

		/// <summary>
		/// The attribute tells if the computed state of the switch is considered open.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean open;
		/// <summary>
		/// The terminal phase at which the connection is applied.   If missing, the
		/// injection is assumed to be balanced among non-neutral phases.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.SinglePhaseKind phase;
		/// <summary>
		/// The switch associated with the switch state.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.Switch Switch;

		public SvSwitch(){

		}

		~SvSwitch(){

		}

		public override void Dispose(){

		}

	}//end SvSwitch

}//end namespace StateVariables