///////////////////////////////////////////////////////////
//  Card.cs
//  Implementation of the Class Card
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:00 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.PaymentMetering;
namespace TC57CIM.IEC61968.PaymentMetering {
	/// <summary>
	/// Documentation of the tender when it is a type of card (credit, debit, etc).
	/// </summary>
	public class Card {

		/// <summary>
		/// Name of account holder.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String accountHolderName;
		/// <summary>
		/// The card verification number.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String cvNumber;
		/// <summary>
		/// The date when this card expires.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Date expiryDate;
		/// <summary>
		/// The primary account number.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String pan;
		/// <summary>
		/// Payment tender this card is being used for.
		/// </summary>
		public TC57CIM.IEC61968.PaymentMetering.Tender Tender;

		public Card(){

		}

		~Card(){

		}

		public virtual void Dispose(){

		}

	}//end Card

}//end namespace PaymentMetering