///////////////////////////////////////////////////////////
//  ChargeKind.cs
//  Implementation of the Class ChargeKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.PaymentMetering {
	/// <summary>
	/// Kind of charge.
	/// </summary>
	public enum ChargeKind : int {

		/// <summary>
		/// The charge levied for the actual usage of the service, normally expressed in
		/// terms of a tariff. For example: usage x price per kWh = total charge for
		/// consumption.
		/// </summary>
		consumptionCharge,
		/// <summary>
		/// The charge related to the usage within a defined time interval, normally
		/// expressed in terms of a tariff. For example: a maximum-demand tariff will levy
		/// an additional charge on top of the consumption charge if the usage exceeds a
		/// defined limit per hour.
		/// </summary>
		demandCharge,
		/// <summary>
		/// Any other charge which is not a consumptionCharge or demandCharge. For example:
		/// debt recovery, arrears, standing charge or charge for another service such as
		/// street lighting.
		/// </summary>
		auxiliaryCharge,
		/// <summary>
		/// Any charge that is classified as a tax of a kind. For example: VAT, GST, TV tax,
		/// etc.
		/// </summary>
		taxCharge,
		/// <summary>
		/// Other kind of charge.
		/// </summary>
		other

	}//end ChargeKind

}//end namespace PaymentMetering