///////////////////////////////////////////////////////////
//  CTTempActivePowerCurve.cs
//  Implementation of the Class CTTempActivePowerCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:45 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// Relationship between the combustion turbine's power output rating in gross
	/// active power (X-axis) and the ambient air temperature (Y-axis).
	/// </summary>
	public class CTTempActivePowerCurve : Curve {

		public CTTempActivePowerCurve(){

		}

		~CTTempActivePowerCurve(){

		}

		public override void Dispose(){

		}

	}//end CTTempActivePowerCurve

}//end namespace GenerationTrainingSimulation