///////////////////////////////////////////////////////////
//  HydroTurbineKind.cs
//  Implementation of the Class HydroTurbineKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// Type of turbine.
	/// </summary>
	public enum HydroTurbineKind : int {

		/// <summary>
		/// Francis.
		/// </summary>
		francis,
		/// <summary>
		/// Pelton.
		/// </summary>
		pelton,
		/// <summary>
		/// Kaplan.
		/// </summary>
		kaplan

	}//end HydroTurbineKind

}//end namespace GenerationTrainingSimulation