///////////////////////////////////////////////////////////
//  ExternalCustomerAgreement.cs
//  Implementation of the Class ExternalCustomerAgreement
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:11 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCustomers {
	/// <summary>
	/// A type of customer agreement involving an external agency. For example, a
	/// customer may form a contracts with an Energy Service Supplier if Direct Access
	/// is permitted.
	/// </summary>
	public class ExternalCustomerAgreement : Agreement {

		public ExternalCustomerAgreement(){

		}

		~ExternalCustomerAgreement(){

		}

		public override void Dispose(){

		}

	}//end ExternalCustomerAgreement

}//end namespace InfCustomers