///////////////////////////////////////////////////////////
//  RemoteSignalKind.cs
//  Implementation of the Class RemoteSignalKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:19 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.Dynamics.StandardInterconnections {
	/// <summary>
	/// Type of input signal coming from remote bus.
	/// </summary>
	public enum RemoteSignalKind : int {

		/// <summary>
		/// Input is voltage frequency from remote terminal bus.
		/// </summary>
		remoteBusVoltageFrequency,
		/// <summary>
		/// Input is voltage frequency deviation from remote terminal bus.
		/// </summary>
		remoteBusVoltageFrequencyDeviation,
		/// <summary>
		/// Input is frequency from remote terminal bus.
		/// </summary>
		remoteBusFrequency,
		/// <summary>
		/// Input is frequency deviation from remote terminal bus.
		/// </summary>
		remoteBusFrequencyDeviation,
		/// <summary>
		/// Input is voltage amplitude from remote terminal bus.
		/// </summary>
		remoteBusVoltageAmplitude,
		/// <summary>
		/// Input is voltage from remote terminal bus.
		/// </summary>
		remoteBusVoltage,
		/// <summary>
		/// Input is branch current amplitude from remote terminal bus.
		/// </summary>
		remoteBranchCurrentAmplitude,
		/// <summary>
		/// Input is branch current amplitude derivative from remote terminal bus.
		/// </summary>
		remoteBusVoltageAmplitudeDerivative,
		/// <summary>
		/// Input is PU voltage derivative from remote terminal bus.
		/// </summary>
		remotePuBusVoltageDerivative

	}//end RemoteSignalKind

}//end namespace StandardInterconnections