///////////////////////////////////////////////////////////
//  AsynchronousMachineDynamics.cs
//  Implementation of the Class AsynchronousMachineDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:40 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Wires;
using TC57CIM.IEC61970.Dynamics.StandardModels;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.AsynchronousMachineDynamics {
	/// <summary>
	/// Asynchronous machine whose behaviour is described by reference to a standard
	/// model expressed in either time constant reactance form or equivalent circuit
	/// form <font color="#0f0f0f">or by definition of a user-defined model.</font>
	/// Parameter details:
	/// <ol>
	/// 	<li>Asynchronous machine parameters such as <i>Xl, Xs,</i> etc. are actually
	/// used as inductances in the model, but are commonly referred to as reactances
	/// since, at nominal frequency, the PU values are the same. However, some
	/// references use the symbol <i>L</i> instead of <i>X</i>.</li>
	/// </ol>
	/// </summary>
	public class AsynchronousMachineDynamics : RotatingMachineDynamics {

		/// <summary>
		/// Asynchronous machine to which this asynchronous machine dynamics model applies.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.AsynchronousMachine AsynchronousMachine;

		public AsynchronousMachineDynamics(){

		}

		~AsynchronousMachineDynamics(){

		}

		public override void Dispose(){

		}

	}//end AsynchronousMachineDynamics

}//end namespace AsynchronousMachineDynamics