///////////////////////////////////////////////////////////
//  BushingInsulationPF.cs
//  Implementation of the Class BushingInsulationPF
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfAssets;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Bushing insulation power factor condition as a result of a test.
	/// Typical status values are: Acceptable, Minor Deterioration or Moisture
	/// Absorption, Major Deterioration or Moisture Absorption, Failed.
	/// </summary>
	public class BushingInsulationPF : IdentifiedObject {

		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// Kind of test for this bushing.
		/// </summary>
		public BushingInsulationPfTestKind testKind;
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.TransformerObservation TransformerObservation;

		public BushingInsulationPF(){

		}

		~BushingInsulationPF(){

		}

		public override void Dispose(){

		}

	}//end BushingInsulationPF

}//end namespace InfAssets