///////////////////////////////////////////////////////////
//  CoolingKind.cs
//  Implementation of the Class CoolingKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of cooling.
	/// </summary>
	public enum CoolingKind : int {

		selfCooling,
		forcedAir,
		forcedOilAndAir,
		other

	}//end CoolingKind

}//end namespace InfAssets