///////////////////////////////////////////////////////////
//  JointFillKind.cs
//  Implementation of the Class JointFillKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of fill for Joint.
	/// </summary>
	public enum JointFillKind : int {

		noFillPrefab,
		airNoFilling,
		petrolatum,
		asphaltic,
		oil,
		bluefill254,
		noVoid,
		epoxy,
		insoluseal,
		other

	}//end JointFillKind

}//end namespace InfAssets