///////////////////////////////////////////////////////////
//  PoleTreatmentKind.cs
//  Implementation of the Class PoleTreatmentKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:20 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of treatment for poles.
	/// </summary>
	public enum PoleTreatmentKind : int {

		full,
		butt,
		natural,
		grayStain,
		greenStain,
		penta,
		unknown,
		other

	}//end PoleTreatmentKind

}//end namespace InfAssets