///////////////////////////////////////////////////////////
//  ReliabilityInfo.cs
//  Implementation of the Class ReliabilityInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61968.InfIEC61968.InfAssets;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Information regarding the experienced and expected reliability of a specific
	/// asset, type of asset, or asset model.
	/// </summary>
	public class ReliabilityInfo : IdentifiedObject {

		/// <summary>
		/// Momentary failure rate (temporary failures/kft-year).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent momFailureRate;
		/// <summary>
		/// Mean time to repair (MTTR - hours).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Hours mTTR;
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset Assets;
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.Specification Specification;

		public ReliabilityInfo(){

		}

		~ReliabilityInfo(){

		}

		public override void Dispose(){

		}

	}//end ReliabilityInfo

}//end namespace InfAssets