///////////////////////////////////////////////////////////
//  StructureMaterialKind.cs
//  Implementation of the Class StructureMaterialKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of material used for structures.
	/// </summary>
	public enum StructureMaterialKind : int {

		wood,
		steel,
		concrete,
		other

	}//end StructureMaterialKind

}//end namespace InfAssets