///////////////////////////////////////////////////////////
//  DemographicKind.cs
//  Implementation of the Class DemographicKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:04 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfLocations {
	/// <summary>
	/// Demographic kind of a land property.
	/// </summary>
	public enum DemographicKind : int {

		urban,
		rural,
		other

	}//end DemographicKind

}//end namespace InfLocations