///////////////////////////////////////////////////////////
//  ACDCConverter.cs
//  Implementation of the Class ACDCConverter
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:38 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// A unit with valves for three phases, together with unit control equipment,
	/// essential protective and switching devices, DC storage capacitors, phase
	/// reactors and auxiliaries, if any, used for conversion.
	/// </summary>
	public class ACDCConverter : ConductingEquipment {

		/// <summary>
		/// Base apparent power of the converter pole. The attribute shall be a positive
		/// value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ApparentPower baseS;
		/// <summary>
		/// Converter DC current, also called Id. It is converter’s state variable, result
		/// from power flow.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow idc;
		/// <summary>
		/// Active power loss in pole at no power transfer. It is converter’s configuration
		/// data used in power flow. The attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower idleLoss;
		/// <summary>
		/// Maximum active power limit. The value is overwritten by values of
		/// VsCapabilityCurve, if present.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower maxP;
		/// <summary>
		/// The maximum voltage on the DC side at which the converter should operate. It is
		/// converter’s configuration data used in power flow. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage maxUdc;
		/// <summary>
		/// Minimum active power limit. The value is overwritten by values of
		/// VsCapabilityCurve, if present.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower minP;
		/// <summary>
		/// The minimum voltage on the DC side at which the converter should operate. It is
		/// converter’s configuration data used in power flow. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage minUdc;
		/// <summary>
		/// Number of valves in the converter. Used in loss calculations.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer numberOfValves;
		/// <summary>
		/// Active power at the point of common coupling. Load sign convention is used, i.e.
		/// positive sign means flow out from a node.
		/// Starting value for a steady state solution in the case a simplified power flow
		/// model is used.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower p;
		/// <summary>
		/// The active power loss at a DC Pole
		/// = idleLoss + switchingLoss*|Idc| + resitiveLoss*Idc^2.
		/// For lossless operation Pdc=Pac.
		/// For rectifier operation with losses Pdc=Pac-lossP.
		/// For inverter operation with losses Pdc=Pac+lossP.
		/// It is converter’s state variable used in power flow. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower poleLossP;
		/// <summary>
		/// Reactive power at the point of common coupling. Load sign convention is used, i.
		/// e. positive sign means flow out from a node.
		/// Starting value for a steady state solution in the case a simplified power flow
		/// model is used.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ReactivePower q;
		/// <summary>
		/// Rated converter DC voltage, also called UdN. The attribute shall be a positive
		/// value. It is converter’s configuration data used in power flow. For instance a
		/// bipolar HVDC link with value  200 kV has a 400kV difference between the dc
		/// lines.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage ratedUdc;
		/// <summary>
		/// It is converter’s configuration data used in power flow. Refer to poleLossP.
		/// The attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance resistiveLoss;
		/// <summary>
		/// Switching losses, relative to the base apparent power 'baseS'. Refer to
		/// poleLossP. The attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePowerPerCurrentFlow switchingLoss;
		/// <summary>
		/// Real power injection target in AC grid, at point of common coupling.  Load sign
		/// convention is used, i.e. positive sign means flow out from a node.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower targetPpcc;
		/// <summary>
		/// Target value for DC voltage magnitude. The attribute shall be a positive value.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage targetUdc;
		/// <summary>
		/// Line-to-line converter voltage, the voltage at the AC side of the valve. It is
		/// converter’s state variable, result from power flow. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage uc;
		/// <summary>
		/// Converter voltage at the DC side, also called Ud. It is converter’s state
		/// variable, result from power flow. The attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage udc;
		/// <summary>
		/// Valve threshold voltage, also called Uvalve. Forward voltage drop when the
		/// valve is conducting. Used in loss calculations, i.e. the switchLoss depend on
		/// numberOfValves * valveU0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage valveU0;
		/// <summary>
		/// Point of common coupling terminal for this converter DC side. It is typically
		/// the terminal on the power transformer (or switch) closest to the AC network.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.Terminal PccTerminal;

		public ACDCConverter(){

		}

		~ACDCConverter(){

		}

		public override void Dispose(){

		}

	}//end ACDCConverter

}//end namespace DC