///////////////////////////////////////////////////////////
//  DCBaseTerminal.cs
//  Implementation of the Class DCBaseTerminal
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.DC;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// An electrical connection point at a piece of DC conducting equipment. DC
	/// terminals are connected at one physical DC node that may have multiple DC
	/// terminals connected. A DC node is similar to an AC connectivity node. The model
	/// requires that DC connections are distinct from AC connections.
	/// </summary>
	public class DCBaseTerminal : ACDCTerminal {

		/// <summary>
		/// See association end Terminal.TopologicalNode.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCTopologicalNode DCTopologicalNode;

		public DCBaseTerminal(){

		}

		~DCBaseTerminal(){

		}

		public override void Dispose(){

		}

	}//end DCBaseTerminal

}//end namespace DC