///////////////////////////////////////////////////////////
//  DCNode.cs
//  Implementation of the Class DCNode
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.DC;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// DC nodes are points where terminals of DC conducting equipment are connected
	/// together with zero impedance.
	/// </summary>
	public class DCNode : IdentifiedObject {

		/// <summary>
		/// DC base terminals interconnected with zero impedance at a this DC connectivity
		/// node.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCBaseTerminal DCTerminals;
		/// <summary>
		/// The DC topological node to which this DC connectivity node is assigned.  May
		/// depend on the current state of switches in the network.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCTopologicalNode DCTopologicalNode;
		/// <summary>
		/// The DC container for the DC nodes.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCEquipmentContainer DCEquipmentContainer;

		public DCNode(){

		}

		~DCNode(){

		}

		public override void Dispose(){

		}

	}//end DCNode

}//end namespace DC