///////////////////////////////////////////////////////////
//  DCTerminal.cs
//  Implementation of the Class DCTerminal
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.DC;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// An electrical connection point to generic DC conducting equipment.
	/// </summary>
	public class DCTerminal : DCBaseTerminal {

		public DCTerminal(){

		}

		~DCTerminal(){

		}

		public override void Dispose(){

		}

	}//end DCTerminal

}//end namespace DC