///////////////////////////////////////////////////////////
//  VsConverter.cs
//  Implementation of the Class VsConverter
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.DC;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// DC side of the voltage source converter (VSC).
	/// </summary>
	public class VsConverter : ACDCConverter {

		/// <summary>
		/// Angle between VsConverter.uv and ACDCConverter.uc. It is converter�s state
		/// variable used in power flow. The attribute shall be a positive value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.AngleDegrees delta;
		/// <summary>
		/// Droop constant. The pu value is obtained as D [kV/MW] x Sb / Ubdc. The
		/// attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU droop;
		/// <summary>
		/// Compensation constant. Used to compensate for voltage drop when controlling
		/// voltage at a distant bus. The attribute shall be a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance droopCompensation;
		/// <summary>
		/// The maximum quotient between the AC converter voltage (Uc) and DC voltage (Ud).
		/// A factor typically less than 1. It is converter�s configuration data used in
		/// power flow.
		/// </summary>
		public float maxModulationIndex;
		/// <summary>
		/// The maximum current through a valve. It is converter�s configuration data.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow maxValveCurrent;
		/// <summary>
		/// Kind of control of real power and/or DC voltage.
		/// </summary>
		public VsPpccControlKind pPccControl;
		/// <summary>
		/// Kind of reactive power control.
		/// </summary>
		public VsQpccControlKind qPccControl;
		/// <summary>
		/// Reactive power sharing factor among parallel converters on Uac control. The
		/// attribute shall be a positive value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent qShare;
		/// <summary>
		/// Phase target at AC side, at point of common coupling. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.AngleDegrees targetPhasePcc;
		/// <summary>
		/// Power factor target at the AC side, at point of common coupling. The attribute
		/// shall be a positive value.
		/// </summary>
		public float targetPowerFactorPcc;
		/// <summary>
		/// Magnitude of pulse-modulation factor. The attribute shall be a positive value.
		/// </summary>
		public float targetPWMfactor;
		/// <summary>
		/// Reactive power injection target in AC grid, at point of common coupling.  Load
		/// sign convention is used, i.e. positive sign means flow out from a node.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ReactivePower targetQpcc;
		/// <summary>
		/// Voltage target in AC grid, at point of common coupling. The attribute shall be
		/// a positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage targetUpcc;
		/// <summary>
		/// Line-to-line voltage on the valve side of the converter transformer. It is
		/// converter�s state variable, result from power flow. The attribute shall be a
		/// positive value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage uv;
		/// <summary>
		/// Capability curve of this converter.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.VsCapabilityCurve CapabilityCurve;

		public VsConverter(){

		}

		~VsConverter(){

		}

		public override void Dispose(){

		}

	}//end VsConverter

}//end namespace DC