///////////////////////////////////////////////////////////
//  EndDeviceEventDetail.cs
//  Implementation of the Class EndDeviceEventDetail
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:07 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Name-value pair, specific to end device events.
	/// </summary>
	public class EndDeviceEventDetail {

		/// <summary>
		/// Name.
		/// </summary>
		public string name;
		/// <summary>
		/// Value, including unit information.
		/// </summary>
		public StringQuantity value;

		public EndDeviceEventDetail(){

		}

		~EndDeviceEventDetail(){

		}

		public virtual void Dispose(){

		}

	}//end EndDeviceEventDetail

}//end namespace Metering