///////////////////////////////////////////////////////////
//  MeasurementKind.cs
//  Implementation of the Class MeasurementKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:15 AM
//  Original author: Margaret
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Kind of read / measured value.
	/// </summary>
	public enum MeasurementKind : int {

		/// <summary>
		/// Not Applicable
		/// </summary>
		none = 0,
		/// <summary>
		/// The ratio of real energy (usually net Wh) to apparent energy (kVAh)
		/// </summary>
		apparentPowerFactor = 2,
		/// <summary>
		/// funds
		/// </summary>
		currency = 3,
		/// <summary>
		/// The flow of electrons
		/// </summary>
		current = 4,
		/// <summary>
		/// A phase current zerocross timing measurement releative to a reference voltage
		/// zerocross
		/// </summary>
		currentAngle = 5,
		/// <summary>
		/// A measurement of the departure of a phase current relative to the average
		/// current of all phases
		/// </summary>
		currentImbalance = 6,
		/// <summary>
		/// A measurement of the date and/or time in a clock, or a time stamp indicating
		/// when data was captured, when a maximum or minimum occurred, or to commemorate
		/// some other important aspect of a measurement
		/// </summary>
		date = 7,
		/// <summary>
		/// The measurement of maximum power flow which is computed as energy usage over
		/// time, the dimensions of which are defined by a tariff
		/// </summary>
		demand = 8,
		/// <summary>
		/// A linear distance or range radius
		/// </summary>
		distance = 9,
		/// <summary>
		/// A measurement in which a V<sup>2</sup> I<sup>2</sup> term has both real and
		/// reactive components removed leaving only distortion. For example, distortion
		/// VAh = Sqrt( (V<sup>2</sup>h)(I<sup>2</sup>h) � (Wh)<sup>2</sup> �
		/// (VArh)<sup>2</sup>)
		/// </summary>
		distortionVoltAmp = 10,
		/// <summary>
		/// Pertaining to the presence of voltage
		/// </summary>
		energization = 11,
		/// <summary>
		/// Scalar quantity which may be increased or decreased in a system when it
		/// receives or produces work, respectively
		/// </summary>
		energy = 12,
		/// <summary>
		/// Measuring the presence or absence of voltage on the load side of an electricity
		/// meter
		/// </summary>
		energizationLoadSide = 13,
		/// <summary>
		/// A forced air moving device
		/// </summary>
		fan = 14,
		/// <summary>
		/// Reciprocal of the period
		/// </summary>
		frequency = 15,
		/// <summary>
		/// Duplicate with �currency�
		/// </summary>
		fund = 16,
		/// <summary>
		/// A measurement of IEEE-1366 Average Service Availability Index
		/// </summary>
		ieee1366ASAI = 17,
		/// <summary>
		/// A measurement of the IEEE-1366 Average Service Interruption Duration Index
		/// </summary>
		ieee1366ASIDI = 18,
		/// <summary>
		/// A measurement of the IEEE-1366 Average Service Interruption Frequency Index
		/// </summary>
		ieee1366ASIFI = 19,
		/// <summary>
		/// A measurement of the IEEE-1366 Customer average interruption duration index
		/// </summary>
		ieee1366CAIDI = 20,
		/// <summary>
		/// A measurement of the IEEE-1366 Customer average interruption frequency index
		/// </summary>
		ieee1366CAIFI = 21,
		/// <summary>
		/// A measurement of the IEEE-1366 Customers Experiencing Multiple Interruptions
		/// </summary>
		ieee1366CEMIn = 22,
		/// <summary>
		/// A measurement of the IEEE-1366 Customers Experiencing Multiple Sustained and
		/// Momentary Interruptions
		/// </summary>
		ieee1366CEMSMIn = 23,
		/// <summary>
		/// A measurement of the IEEE-1366 Customer Total Average Interruption Duration
		/// Index
		/// </summary>
		ieee1366CTAIDI = 24,
		/// <summary>
		/// A measurement of the IEEE-1366 Momentary Average Interruption Frequency Index
		/// </summary>
		ieee1366MAIFI = 25,
		/// <summary>
		/// A measurement of the IEEE-1366 Momentary Average event Interruption Frequency
		/// Index
		/// </summary>
		ieee1366MAIFIe = 26,
		/// <summary>
		/// IEEE-1366 System Average Interruption Duration Index
		/// </summary>
		ieee1366SAIDI = 27,
		/// <summary>
		/// IEEE-1366 System Average Interruption Frequency Index
		/// </summary>
		ieee1366SAIFI = 28,
		/// <summary>
		/// An energy, power, voltage, or current loss attributed to transmission or
		/// distribution line impedance
		/// </summary>
		lineLoss = 31,
		/// <summary>
		/// A quantity lost due to �technical� reasons (such as line loss) or �non-
		/// technical� reasons (such as theft.)
		/// </summary>
		loss = 32,
		/// <summary>
		/// A quantity that has a rotation sequence which is opposite to that of the power
		/// system
		/// </summary>
		negativeSequence = 33,
		/// <summary>
		/// The ratio of real energy (usually net Wh) to phasor apparent energy (kVAh)
		/// </summary>
		phasorPowerFactor = 34,
		/// <summary>
		/// The ratio of real energy (usually net Wh) to phasor reactive energy (kVAh)
		/// </summary>
		phasorReactivePower = 35,
		/// <summary>
		/// A quantity that has a rotation sequence in agreement with that of the power
		/// system
		/// </summary>
		positiveSequence = 36,
		/// <summary>
		/// The derivative of energy with respect to time, where the energy is being
		/// transferred or transformed.
		/// </summary>
		power = 37,
		/// <summary>
		/// The ratio of real energy (usually net Wh) to apparent energy (kVAh)
		/// </summary>
		powerFactor = 38,
		/// <summary>
		/// A power measurement of Qh, where Qh is defined to be half of the sum of the Wh
		/// measurements on each phase plus the squareroot of 3 over two times the sum of
		/// the VArh measurements on each phase.
		/// </summary>
		quantityPower = 40,
		/// <summary>
		/// A temporary dip in the supply voltage below the nominal value
		/// </summary>
		sag = 41,
		/// <summary>
		/// A temporary rise of the supply voltage over the nominal value
		/// </summary>
		swell = 42,
		/// <summary>
		/// A physical or logical switch position status which includes �opened� and
		/// �closed�, but for some products may also include �armed,� or other states that
		/// indicate a temporary state due to some condition.
		/// </summary>
		switchPosition = 43,
		/// <summary>
		/// Tap changer position
		/// </summary>
		tapPosition = 44,
		/// <summary>
		/// An energy price defined in a contract. The rate might be a price for energy,
		/// for power (usually expressed as a demand value), or some other measurement. The
		/// rate might be currency based, or as a code, or as a component of a larger
		/// tariff description.
		/// </summary>
		tariffRate = 45,
		/// <summary>
		/// A quantity proportional to the energy of a system
		/// </summary>
		temperature = 46,
		/// <summary>
		/// The ratio of the sum of the harmonics to the fundamental. (THD may measure
		/// either voltage or current, and may isolated to a given phase)
		/// </summary>
		totalHarmonicDistortion = 47,
		/// <summary>
		/// A measurement of the energy or power loss in a transformer due to inefficiency
		/// </summary>
		transformerLoss = 48,
		/// <summary>
		/// A voltage dip classification per EN50160 or a similar national standard
		/// measuring the number of dips in the 10-15% range
		/// </summary>
		unipedeVoltageDip10to15 = 49,
		/// <summary>
		/// A voltage dip classification per EN50160 or a similar national standard
		/// measuring the number of dips in the 15-30% range
		/// </summary>
		unipedeVoltageDip15to30 = 50,
		/// <summary>
		/// A voltage dip classification per EN50160 or a similar national standard
		/// measuring the number of dips in the 30-60% range
		/// </summary>
		unipedeVoltageDip30to60 = 51,
		/// <summary>
		/// A voltage dip classification per EN50160 or a similar national standard
		/// measuring the number of dips in the 60-90% rangeA voltage dip classification
		/// per EN50160 or a similar national standard measuring the number of dips in the
		/// 60-90% range
		/// </summary>
		unipedeVoltageDip60to90 = 52,
		/// <summary>
		/// A voltage dip classification per EN50160 or a similar national standard
		/// measuring the number of dips in the 90-100% range
		/// </summary>
		unipedeVoltageDip90to100 = 53,
		/// <summary>
		/// The difference in electric potential between two points
		/// </summary>
		voltage = 54,
		/// <summary>
		/// A phase voltage zerocross timing measurement relative to a reference voltage
		/// zerocross
		/// </summary>
		voltageAngle = 55,
		/// <summary>
		/// A measurement of the departure of the voltage from the nominal voltage
		/// </summary>
		voltageExcursion = 56,
		/// <summary>
		/// A measurement of the departure of a phase voltage relative to the average
		/// voltage of all phases.
		/// </summary>
		voltageImbalance = 57,
		/// <summary>
		/// fluid volume
		/// </summary>
		volume = 58,
		/// <summary>
		/// The amount of time that current flow drops to a zero level or level below the
		/// ability of the sensor to sense
		/// </summary>
		zeroFlowDuration = 59,
		/// <summary>
		/// The zero sequence current is the vector sum of the phase currents
		/// </summary>
		zeroSequence = 60,
		/// <summary>
		/// The ratio of the distortion VAh to the apparent VAh
		/// </summary>
		distortionPowerFactor = 64,
		/// <summary>
		/// A measurement of the departure of the frequency from the nominal frequency
		/// </summary>
		frequencyExcursion = 81,
		/// <summary>
		/// Information that describes the logical context in which a request, measurement,
		/// or command is made.
		/// </summary>
		applicationContext = 90,
		/// <summary>
		/// An application name which is making or has made a request
		/// </summary>
		apTitle = 91,
		/// <summary>
		/// An asset identifier
		/// </summary>
		assetNumber = 92,
		/// <summary>
		/// A measurement of dataflow
		/// </summary>
		bandwidth = 93,
		/// <summary>
		/// Battery voltage
		/// </summary>
		batteryVoltage = 94,
		/// <summary>
		/// A message target address implying all endpoint units within range of a
		/// particular sender
		/// </summary>
		broadcastAddress = 95,
		/// <summary>
		/// Endpoint target address Type1
		/// </summary>
		deviceAddressType1 = 96,
		/// <summary>
		/// Endpoint target address Type2
		/// </summary>
		deviceAddressType2 = 97,
		/// <summary>
		/// Endpoint target address Type3
		/// </summary>
		deviceAddressType3 = 98,
		/// <summary>
		/// Endpoint target address Type4
		/// </summary>
		deviceAddressType4 = 99,
		/// <summary>
		/// A unique identifier for the Endpoint�s configuration
		/// </summary>
		deviceClass = 100,
		/// <summary>
		/// A device serial number
		/// </summary>
		electronicSerialNumber = 101,
		/// <summary>
		/// A unique identifier of the endDevice � the device providing measurements or
		/// under control of the network
		/// </summary>
		endDeviceID = 102,
		/// <summary>
		/// Group target address Type1
		/// </summary>
		groupAddressType1 = 103,
		/// <summary>
		/// Group target address Type2
		/// </summary>
		groupAddressType2 = 104,
		/// <summary>
		/// Group target address Type3
		/// </summary>
		groupAddressType3 = 105,
		/// <summary>
		/// Group target address Type4
		/// </summary>
		groupAddressType4 = 106,
		/// <summary>
		/// An IP address for the endpoint
		/// </summary>
		ipAddress = 107,
		/// <summary>
		/// A MAC address for the endpoint
		/// </summary>
		macAddress = 108,
		/// <summary>
		/// The configuration given to a device at time of manufacture
		/// </summary>
		mfgAssignedConfigurationID = 109,
		/// <summary>
		/// The serial number assigned to a device at time of manufacture
		/// </summary>
		mfgAssignedPhysicalSerialNumber = 110,
		/// <summary>
		/// The product number assigned to a device at time of manufacture
		/// </summary>
		mfgAssignedProductNumber = 111,
		/// <summary>
		/// A communication address assigned to a device at time of manufacture
		/// </summary>
		mfgAssignedUniqueCommunicationAddress = 112,
		/// <summary>
		/// A message target address implying a large group of endpoint units within range
		/// of a particular sender
		/// </summary>
		multiCastAddress = 113,
		/// <summary>
		/// A communication address of a network endpoint used in one-way communication
		/// </summary>
		oneWayAddress = 114,
		/// <summary>
		/// A measurement of RF signal strength
		/// </summary>
		signalStrength = 115,
		/// <summary>
		/// A communication address used for bidirectional communication
		/// </summary>
		twoWayAddress = 116,
		/// <summary>
		/// A measurement of received (RF) signal strength divided by the (RF) noise floor
		/// </summary>
		signaltoNoiseRatio = 117,
		/// <summary>
		/// A measurement related to an alarm
		/// </summary>
		alarm = 118,
		/// <summary>
		/// An estimate of the battery ride through capacity
		/// </summary>
		batteryCarryover = 119,
		/// <summary>
		/// An indication of or measurement of a loss of data
		/// </summary>
		dataOverflowAlarm = 120,
		/// <summary>
		/// A threshold setting that determines the trip point that if exceeded would
		/// trigger a demand limiting action or alarm
		/// </summary>
		demandLimit = 121,
		/// <summary>
		/// A count of the number of times demand has been reset (remotely, locally, and/or
		/// automatically.)
		/// </summary>
		demandReset = 122,
		/// <summary>
		/// A measurement related to equipment diagnostics
		/// </summary>
		diagnostic = 123,
		/// <summary>
		/// A setting that indicates an emergency limit
		/// </summary>
		emergencyLimit = 124,
		/// <summary>
		/// An indication of tampering with a meter encoder
		/// </summary>
		encoderTamper = 125,
		/// <summary>
		/// IEEE-1366 Momentary Interruption count
		/// </summary>
		ieee1366MomentaryInterruption = 126,
		/// <summary>
		/// IEEE-1366 Momentary Interruption event count
		/// </summary>
		ieee1366MomentaryInterruptionEvent = 127,
		/// <summary>
		/// IEEE-1366 Sustained Interruption duration
		/// </summary>
		ieee1366SustainedInterruption = 128,
		/// <summary>
		/// A measurement related to power interruptions (Note: often an interruption count
		/// or duration.)
		/// </summary>
		interruptionBehaviour = 129,
		/// <summary>
		/// A measurement related to inversion tamper (Note: typically a count of
		/// inversions)
		/// </summary>
		inversionTamper = 130,
		/// <summary>
		/// A measurement related to load interruption (Note: typically a load interruption
		/// count or measurement of duration)
		/// </summary>
		loadInterrupt = 131,
		/// <summary>
		/// A measurement related to load shed (Note: typically a load shed count or load
		/// shed duration)
		/// </summary>
		loadShed = 132,
		/// <summary>
		/// A measurement related to the pending maintenance of equipment
		/// </summary>
		maintenance = 133,
		/// <summary>
		/// A measurement related to physical tampering (Note: typically a tamper count)
		/// </summary>
		physicalTamper = 134,
		/// <summary>
		/// Tamper indicated while power was out
		/// </summary>
		powerLossTamper = 135,
		/// <summary>
		/// A measurement related to power outages (Note: typically a status)
		/// </summary>
		powerOutage = 136,
		/// <summary>
		/// A measurement related to power quality
		/// </summary>
		powerQuality = 137,
		/// <summary>
		/// A measurement related to power restoration (Note: typically a status)
		/// </summary>
		powerRestoration = 138,
		/// <summary>
		/// A measurement related to device programming (Note: typically a status
		/// measurement)
		/// </summary>
		programmed = 139,
		/// <summary>
		/// A measurement related to pushbutton (Note: typically a status or count)
		/// </summary>
		pushbutton = 140,
		/// <summary>
		/// A measurement related to relay activations
		/// </summary>
		relayActivation = 141,
		/// <summary>
		/// A measurement related to relay cycling (Note1: one open and one closure
		/// together is one cycle, Note2: Usually expressed as a count)
		/// </summary>
		relayCycle = 142,
		/// <summary>
		/// An indication of equipment tampering that shows equipment was moved or opened
		/// </summary>
		removalTamper = 143,
		/// <summary>
		/// An indication of equipment tampering that shows equipment has been
		/// reprogrammed
		/// </summary>
		reprogrammingTamper = 144,
		/// <summary>
		/// An indication of tampering as evidenced by reverse power flow
		/// </summary>
		reverseRotationTamper = 145,
		/// <summary>
		/// A measurement of the switch arm condition
		/// </summary>
		switchArmed = 146,
		/// <summary>
		/// A measurement of the switch enablement status
		/// </summary>
		switchDisabled = 147,
		/// <summary>
		/// An indication of equipment tampering
		/// </summary>
		tamper = 148,
		/// <summary>
		/// A reset triggered by a hardware �watchdog� circuit
		/// </summary>
		watchdogTimeout = 149,
		/// <summary>
		/// Customer�s bill for the previous billing period (Currency)
		/// </summary>
		billLastPeriod = 150,
		/// <summary>
		/// Customer�s bill, as known thus far within the present billing period
		/// (Currency)
		/// </summary>
		billToDate = 151,
		/// <summary>
		/// Customer�s bill for the (Currency)
		/// </summary>
		billCarryover = 152,
		/// <summary>
		/// Monthly fee for connection to commodity.
		/// </summary>
		connectionFee = 153,
		/// <summary>
		/// Sound
		/// </summary>
		audibleVolume = 154,
		/// <summary>
		/// A fluid flow rate
		/// </summary>
		volumetricFlow = 155

	}//end MeasurementKind

}//end namespace Metering