///////////////////////////////////////////////////////////
//  ReadingReasonKind.cs
//  Implementation of the Class ReadingReasonKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Reason for the reading being taken.
	/// </summary>
	public enum ReadingReasonKind : int {

		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with installation of a meter.
		/// </summary>
		installation,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with removal of a meter.
		/// </summary>
		removal,
		/// <summary>
		/// Reading(s) taken or to be taken in response to an inquiry by a customer or
		/// other party.
		/// </summary>
		inquiry,
		/// <summary>
		/// Reading(s) taken or to be taken in response to a billing-related inquiry by a
		/// customer or other party. A variant of 'inquiry'.
		/// </summary>
		billing,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with a customer move-in event.
		/// </summary>
		moveIn,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with a customer move-out event.
		/// </summary>
		moveOut,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with the resetting of one or
		/// more demand registers in a meter.
		/// </summary>
		demandReset,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with a disconnection of service.
		/// 
		/// </summary>
		serviceDisconnect,
		/// <summary>
		/// Reading(s) taken or to be taken in conjunction with a connection or re-
		/// connection of service.
		/// </summary>
		serviceConnect,
		/// <summary>
		/// Reading(s) taken or to be taken to support management of loads on distribution
		/// networks or devices.
		/// </summary>
		loadManagement,
		/// <summary>
		/// Reading(s) taken or to be taken to support research and analysis of loads on
		/// distribution networks or devices.
		/// </summary>
		loadResearch,
		/// <summary>
		/// Reading(s) taken or to be taken for some other reason or purpose.
		/// </summary>
		other

	}//end ReadingReasonKind

}//end namespace Metering