///////////////////////////////////////////////////////////
//  SimpleEndDeviceFunction.cs
//  Implementation of the Class SimpleEndDeviceFunction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Metering;
namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Simple end device function distinguished by 'kind'. Use this class for
	/// instances that cannot be represented by another end device function
	/// specialisations.
	/// </summary>
	public class SimpleEndDeviceFunction : EndDeviceFunction {

		/// <summary>
		/// Kind of this function.
		/// </summary>
		public EndDeviceFunctionKind kind;

		public SimpleEndDeviceFunction(){

		}

		~SimpleEndDeviceFunction(){

		}

		public override void Dispose(){

		}

	}//end SimpleEndDeviceFunction

}//end namespace Metering