///////////////////////////////////////////////////////////
//  OperationsSafetySupervisor.cs
//  Implementation of the Class OperationsSafetySupervisor
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Operations;
using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Operator with responsibility that the work in high voltage installation is
	/// executed in a safe manner and according to safety regulation.
	/// </summary>
	public class OperationsSafetySupervisor : Operator {

		/// <summary>
		/// All safety documents issued by this supervisor.
		/// </summary>
		public TC57CIM.IEC61968.Operations.SafetyDocument IssuedSafetyDocuments;
		/// <summary>
		/// All safety documents released to this supervisor.
		/// </summary>
		public TC57CIM.IEC61968.Operations.SafetyDocument ReleasedSafetyDocuments;

		public OperationsSafetySupervisor(){

		}

		~OperationsSafetySupervisor(){

		}

		public override void Dispose(){

		}

	}//end OperationsSafetySupervisor

}//end namespace Operations