///////////////////////////////////////////////////////////
//  RevisionKind.cs
//  Implementation of the Class RevisionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:23 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// List of the kinds of revisions that can be made to a SwitchingStep.
	/// </summary>
	public enum RevisionKind : int {

		void_,
		added

	}//end RevisionKind

}//end namespace Operations