///////////////////////////////////////////////////////////
//  SafetyDocument.cs
//  Implementation of the Class SafetyDocument
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:23 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Document restricting or authorising works on electrical equipment (for example
	/// a permit to work, sanction for test, limitation of access, or certificate of
	/// isolation), defined based upon organisational practices.
	/// </summary>
	public class SafetyDocument : Document {

		/// <summary>
		/// Date and time this safety document has been issued.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime issuedDateTime;
		/// <summary>
		/// Date and time this safety document has been released.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime releasedDateTime;

		public SafetyDocument(){

		}

		~SafetyDocument(){

		}

		public override void Dispose(){

		}

	}//end SafetyDocument

}//end namespace Operations