///////////////////////////////////////////////////////////
//  TagAction.cs
//  Implementation of the Class TagAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:27 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Operations;
namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Action on operation tag as a switching step.
	/// </summary>
	public class TagAction : SwitchingAction {

		/// <summary>
		/// Kind of tag action.
		/// </summary>
		public TagActionKind kind;
		/// <summary>
		/// Tag associated with this tag action.
		/// </summary>
		public TC57CIM.IEC61968.Operations.OperationalTag OperationalTag;

		public TagAction(){

		}

		~TagAction(){

		}

		public override void Dispose(){

		}

	}//end TagAction

}//end namespace Operations