///////////////////////////////////////////////////////////
//  UnderexcLim2Simplified.cs
//  Implementation of the Class UnderexcLim2Simplified
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:28 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.UnderexcitationLimiterDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.UnderexcitationLimiterDynamics {
	/// <summary>
	/// Simplified type UEL2 underexcitation limiter.  This model can be derived from
	/// UnderexcLimIEEE2.  The limit characteristic (look �up table) is a single
	/// straight-line, the same as UnderexcLimIEEE2 (see Figure 10.4 (p 32), IEEE 421.5-
	/// 2005 Section 10.2).
	/// </summary>
	public class UnderexcLim2Simplified : UnderexcitationLimiterDynamics {

		/// <summary>
		/// Gain Under excitation limiter (<i>K</i><i><sub>UI</sub></i>).  Typical value =
		/// 0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kui;
		/// <summary>
		/// Segment P initial point (<i>P</i><i><sub>0</sub></i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU p0;
		/// <summary>
		/// Segment P end point (<i>P</i><i><sub>1</sub></i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU p1;
		/// <summary>
		/// Segment Q initial point (<i>Q</i><i><sub>0</sub></i>).  Typical value = -0,31.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU q0;
		/// <summary>
		/// Segment Q end point (<i>Q</i><i><sub>1</sub></i>).  Typical value = -0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU q1;
		/// <summary>
		/// Maximum error signal (<i>V</i><i><sub>UIMAX</sub></i>) (>
		/// UnderexcLim2Simplified.vuimin).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vuimax;
		/// <summary>
		/// Minimum error signal (<i>V</i><i><sub>UIMIN</sub></i>) (<
		/// UnderexcLim2Simplified.vuimax).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vuimin;

		public UnderexcLim2Simplified(){

		}

		~UnderexcLim2Simplified(){

		}

		public override void Dispose(){

		}

	}//end UnderexcLim2Simplified

}//end namespace UnderexcitationLimiterDynamics