///////////////////////////////////////////////////////////
//  ModelAuthority.cs
//  Implementation of the Class ModelAuthority
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A Modeling Authority is an entity responsible for supplying and maintaining the
	/// data defining a specific set of objects in a network model.
	/// </summary>
	public class ModelAuthority : IdentifiedObject {

		public ModelAuthority(){

		}

		~ModelAuthority(){

		}

		public override void Dispose(){

		}

	}//end ModelAuthority

}//end namespace NetworkModelFrames