///////////////////////////////////////////////////////////
//  Operation.cs
//  Implementation of the Class Operation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	public class Operation {

		public Operation(){

		}

		~Operation(){

		}

		public virtual void Dispose(){

		}

	}//end Operation

}//end namespace NetworkModelFrames