///////////////////////////////////////////////////////////
//  Author.cs
//  Implementation of the Class Author
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Person who created document or activity record.
	/// </summary>
	public class Author : DocumentPersonRole {

		/// <summary>
		/// All documents of this this author.
		/// </summary>
		public TC57CIM.IEC61968.Common.Document Documents;
		/// <summary>
		/// All activity records with this author.
		/// </summary>
		public TC57CIM.IEC61968.Common.ActivityRecord ActivityRecords;

		public Author(){

		}

		~Author(){

		}

		public override void Dispose(){

		}

	}//end Author

}//end namespace Common