///////////////////////////////////////////////////////////
//  ConfigurationEvent.cs
//  Implementation of the Class ConfigurationEvent
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61970.Base.Faults;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Used to report details on creation, change or deletion of an entity or its
	/// configuration.
	/// </summary>
	public class ConfigurationEvent : ActivityRecord {

		/// <summary>
		/// Date and time this event has or will become effective.
		/// </summary>
		public System.DateTime effectiveDateTime;
		/// <summary>
		/// Source/initiator of modification.
		/// </summary>
		public string modifiedBy;
		/// <summary>
		/// Free text remarks.
		/// </summary>
		public string remark;
		/// <summary>
		/// Fault cause type whose change resulted in this configuration event.
		/// </summary>
		public TC57CIM.IEC61970.Base.Faults.FaultCauseType FaultCauseType;

		public ConfigurationEvent(){

		}

		~ConfigurationEvent(){

		}

		public override void Dispose(){

		}

	}//end ConfigurationEvent

}//end namespace Common