///////////////////////////////////////////////////////////
//  ElectronicAddress.cs
//  Implementation of the Class ElectronicAddress
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:06 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Electronic address information.
	/// </summary>
	public class ElectronicAddress {

		/// <summary>
		/// Primary email address.
		/// </summary>
		public string email1;
		/// <summary>
		/// Alternate email address.
		/// </summary>
		public string email2;
		/// <summary>
		/// Address on local area network.
		/// </summary>
		public string lan;
		/// <summary>
		/// MAC (Media Access Control) address.
		/// </summary>
		public string mac;
		/// <summary>
		/// Password needed to log in.
		/// </summary>
		public string password;
		/// <summary>
		/// Radio address.
		/// </summary>
		public string radio;
		/// <summary>
		/// User ID needed to log in, which can be for an individual person, an
		/// organisation, a location, etc.
		/// </summary>
		public string userID;
		/// <summary>
		/// World wide web address.
		/// </summary>
		public string web;

		public ElectronicAddress(){

		}

		~ElectronicAddress(){

		}

		public virtual void Dispose(){

		}

	}//end ElectronicAddress

}//end namespace Common