///////////////////////////////////////////////////////////
//  FieldDispatchStep.cs
//  Implementation of the Class FieldDispatchStep
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:11 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Details of the step in the field dispatch history.
	/// </summary>
	public class FieldDispatchStep {

		/// <summary>
		/// The status of one or more crews dispatched to perform field work at one or more
		/// work sites
		/// </summary>
		public CrewStatusKind dispatchStatus;
		/// <summary>
		/// The date and time at which the dispatch status occurred.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime occurredDateTime;
		/// <summary>
		/// freeform comments related to the dispatch to perform field work.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String remarks;
		/// <summary>
		/// The sequence number of the field dispatch step within the field dispatch
		/// history.  Begins with 1 and increments up.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer sequenceNumber;

		public FieldDispatchStep(){

		}

		~FieldDispatchStep(){

		}

		public virtual void Dispose(){

		}

	}//end FieldDispatchStep

}//end namespace Common