///////////////////////////////////////////////////////////
//  OperationPersonRole.cs
//  Implementation of the Class OperationPersonRole
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Person role in the context of utility operations.
	/// </summary>
	public class OperationPersonRole : PersonRole {

		public OperationPersonRole(){

		}

		~OperationPersonRole(){

		}

		public override void Dispose(){

		}

	}//end OperationPersonRole

}//end namespace Common