///////////////////////////////////////////////////////////
//  TroubleReporter.cs
//  Implementation of the Class TroubleReporter
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Customers;
using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Type of Person reporting the Trouble - Customer, First Responder, Passer-by,
	/// etc.
	/// </summary>
	public class TroubleReporter : OperationPersonRole {

		/// <summary>
		/// The type of person reporting the trouble
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String troubleReporterType;
		public TC57CIM.IEC61968.Customers.TroubleTicket TroubleTicket;

		public TroubleReporter(){

		}

		~TroubleReporter(){

		}

		public override void Dispose(){

		}

	}//end TroubleReporter

}//end namespace Common