///////////////////////////////////////////////////////////
//  AssetTemperaturePressureAnalog.cs
//  Implementation of the Class AssetTemperaturePressureAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetMeas;
namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Temperature or pressure type of asset analog.
	/// </summary>
	public class AssetTemperaturePressureAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing temperature or pressure related to an asset.
		/// </summary>
		public AssetTemperaturePressureAnalogKind kind;

		public AssetTemperaturePressureAnalog(){

		}

		~AssetTemperaturePressureAnalog(){

		}

		public override void Dispose(){

		}

	}//end AssetTemperaturePressureAnalog

}//end namespace AssetMeas