///////////////////////////////////////////////////////////
//  PFVArType2IEEEPFController.cs
//  Implementation of the Class PFVArType2IEEEPFController
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: pcha006
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType2Dynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType2Dynamics {
	/// <summary>
	/// IEEE PF controller type 2 which is a summing point type controller making up
	/// the outside loop of a two-loop system. This controller is implemented as a slow
	/// PI type controller. The voltage regulator forms the inner loop and is
	/// implemented as a fast controller.
	/// Reference: IEEE 421.5-2005, 11.4.
	/// </summary>
	public class PFVArType2IEEEPFController : PFVArControllerType2Dynamics {

		/// <summary>
		/// Overexcitation or under excitation flag (<i>EXLON</i>)
		/// true = 1 (not in the overexcitation or underexcitation state, integral action
		/// is active)
		/// false = 0 (in the overexcitation or underexcitation state, so integral action
		/// is disabled to allow the limiter to play its role).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean exlon;
		/// <summary>
		/// Integral gain of the pf controller (<i>K</i><i><sub>I</sub></i>).  Typical
		/// value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU ki;
		/// <summary>
		/// Proportional gain of the pf controller (<i>K</i><i><sub>P</sub></i>).  Typical
		/// value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kp;
		/// <summary>
		/// Power factor reference (<i>P</i><i><sub>FREF</sub></i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pfref;
		/// <summary>
		/// Maximum output of the pf controller (<i>V</i><i><sub>CLMT</sub></i>).  Typical
		/// value = 0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vclmt;
		/// <summary>
		/// Voltage regulator reference (<i>V</i><i><sub>REF</sub></i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vref;
		/// <summary>
		/// Generator sensing voltage (<i>V</i><i><sub>S</sub></i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float vs;

		public PFVArType2IEEEPFController(){

		}

		~PFVArType2IEEEPFController(){

		}

		public override void Dispose(){

		}

	}//end PFVArType2IEEEPFController

}//end namespace PFVArControllerType2Dynamics