///////////////////////////////////////////////////////////
//  BatteryStateKind.cs
//  Implementation of the Class BatteryStateKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: msphuku2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// The state of the battery unit.
	/// </summary>
	public enum BatteryStateKind : int {

		/// <summary>
		/// Stored energy is decreasing.
		/// </summary>
		discharging,
		/// <summary>
		/// Unable to charge, and not discharging.
		/// </summary>
		full,
		/// <summary>
		/// Neither charging nor discharging, but able to do so.
		/// </summary>
		waiting,
		/// <summary>
		/// Stored energy is increasing.
		/// </summary>
		charging,
		/// <summary>
		/// Unable to discharge, and not charging.
		/// </summary>
		empty

	}//end BatteryStateKind

}//end namespace Production