///////////////////////////////////////////////////////////
//  BatteryUnit.cs
//  Implementation of the Class BatteryUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Generation.Production;
using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// An electrochemical energy storage device.
	/// </summary>
	public class BatteryUnit : PowerElectronicsUnit {

		/// <summary>
		/// The current state of the battery (charging, full, etc.).
		/// </summary>
		public BatteryStateKind batteryState;
		/// <summary>
		/// Full energy storage capacity of the battery. The attribute shall be a positive
		/// value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.RealEnergy ratedE;
		/// <summary>
		/// Amount of energy currently stored. The attribute shall be a positive value or
		/// zero and lower than BatteryUnit.ratedE.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.RealEnergy storedE;

		public BatteryUnit(){

		}

		~BatteryUnit(){

		}

		public override void Dispose(){

		}

	}//end BatteryUnit

}//end namespace Production