///////////////////////////////////////////////////////////
//  GeneratorControlSource.cs
//  Implementation of the Class GeneratorControlSource
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:57 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// The source of controls for a generating unit.
	/// </summary>
	public enum GeneratorControlSource : int {

		/// <summary>
		/// Not available.
		/// </summary>
		unavailable,
		/// <summary>
		/// Off of automatic generation control (AGC).
		/// </summary>
		offAGC,
		/// <summary>
		/// On automatic generation control (AGC).
		/// </summary>
		onAGC,
		/// <summary>
		/// Plant is controlling.
		/// </summary>
		plantControl

	}//end GeneratorControlSource

}//end namespace Production