///////////////////////////////////////////////////////////
//  HeatRateCurve.cs
//  Implementation of the Class HeatRateCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:00 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between unit heat rate per active power (Y-axis) and  unit output
	/// (X-axis). The heat input is from all fuels.
	/// </summary>
	public class HeatRateCurve : Curve {

		/// <summary>
		/// Flag is set to true when output is expressed in net active power.
		/// </summary>
		public bool isNetGrossP;

		public HeatRateCurve(){

		}

		~HeatRateCurve(){

		}

		public override void Dispose(){

		}

	}//end HeatRateCurve

}//end namespace Production