///////////////////////////////////////////////////////////
//  StartIgnFuelCurve.cs
//  Implementation of the Class StartIgnFuelCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Generation.Production;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// The quantity of ignition fuel (Y-axis) used to restart and repay the auxiliary
	/// power consumed versus the number of hours (X-axis) the unit was off line.
	/// </summary>
	public class StartIgnFuelCurve : Curve {

		/// <summary>
		/// Type of ignition fuel.
		/// </summary>
		public FuelType ignitionFuelType;

		public StartIgnFuelCurve(){

		}

		~StartIgnFuelCurve(){

		}

		public override void Dispose(){

		}

	}//end StartIgnFuelCurve

}//end namespace Production