///////////////////////////////////////////////////////////
//  AnalogLimit.cs
//  Implementation of the Class AnalogLimit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Meas;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Limit values for Analog measurements.
	/// </summary>
	public class AnalogLimit : Limit {

		/// <summary>
		/// The value to supervise against.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float value;

		public AnalogLimit(){

		}

		~AnalogLimit(){

		}

		public override void Dispose(){

		}

	}//end AnalogLimit

}//end namespace Meas