///////////////////////////////////////////////////////////
//  Discrete.cs
//  Implementation of the Class Discrete
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:48 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Meas;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Discrete represents a discrete Measurement, i.e. a Measurement representing
	/// discrete values, e.g. a Breaker position.
	/// </summary>
	public class Discrete : Measurement {

		/// <summary>
		/// Normal value range maximum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer maxValue;
		/// <summary>
		/// Normal value range minimum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer minValue;
		/// <summary>
		/// Normal measurement value, e.g., used for percentage calculations.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer normalValue;
		/// <summary>
		/// The values connected to this measurement.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.DiscreteValue DiscreteValues;

		public Discrete(){

		}

		~Discrete(){

		}

		public override void Dispose(){

		}

	}//end Discrete

}//end namespace Meas