///////////////////////////////////////////////////////////
//  MeasurementValueQuality.cs
//  Implementation of the Class MeasurementValueQuality
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Meas;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Measurement quality flags. Bits 0-10 are defined for substation automation in
	/// IEC 61850-7-3. Bits 11-15 are reserved for future expansion by that document.
	/// Bits 16-31 are reserved for EMS applications.
	/// </summary>
	public class MeasurementValueQuality : Quality61850 {

		public MeasurementValueQuality(){

		}

		~MeasurementValueQuality(){

		}

		public override void Dispose(){

		}

	}//end MeasurementValueQuality

}//end namespace Meas