///////////////////////////////////////////////////////////
//  StringMeasurementValue.cs
//  Implementation of the Class StringMeasurementValue
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:22 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Meas;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// StringMeasurementValue represents a measurement value of type string.
	/// </summary>
	public class StringMeasurementValue : MeasurementValue {

		/// <summary>
		/// The value to supervise.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String value;
		/// <summary>
		/// Measurement to which this value is connected.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.StringMeasurement StringMeasurement;

		public StringMeasurementValue(){

		}

		~StringMeasurementValue(){

		}

		public override void Dispose(){

		}

	}//end StringMeasurementValue

}//end namespace Meas