///////////////////////////////////////////////////////////
//  BlockDispatchComponent.cs
//  Implementation of the Class BlockDispatchComponent
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.InfIEC61970.EnergyArea;
namespace TC57CIM.IEC61970.InfIEC61970.EnergyArea {
	public class BlockDispatchComponent : EnergyComponent {

		public BlockDispatchComponent(){

		}

		~BlockDispatchComponent(){

		}

		public override void Dispose(){

		}

	}//end BlockDispatchComponent

}//end namespace EnergyArea