///////////////////////////////////////////////////////////
//  Pcontrol.cs
//  Implementation of the Class Pcontrol
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:11 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	public class Pcontrol {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1 VSCtype1;

		public Pcontrol(){

		}

		~Pcontrol(){

		}

		public virtual void Dispose(){

		}

	}//end Pcontrol

}//end namespace VSC