///////////////////////////////////////////////////////////
//  Qlimiter.cs
//  Implementation of the Class Qlimiter
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:18 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	public class Qlimiter {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1 VSCtype1;

		public Qlimiter(){

		}

		~Qlimiter(){

		}

		public virtual void Dispose(){

		}

	}//end Qlimiter

}//end namespace VSC