///////////////////////////////////////////////////////////
//  DERGroupForecast.cs
//  Implementation of the Class DERGroupForecast
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:04 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61968.Metering;
namespace TC57CIM.IEC61968.DER {
	/// <summary>
	/// Specifies the forecasted values of the DERMonitorableParameters for a DER Group
	/// over a specific time interval.
	/// </summary>
	public class DERGroupForecast : IdentifiedObject {

		/// <summary>
		/// The timestamp for when the DER Group forecast was created
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime predictionCreationDate;
		/// <summary>
		/// The DER Group for which forecasts are made.
		/// </summary>
		public TC57CIM.IEC61968.Metering.EndDeviceGroup EndDeviceGroup;

		public DERGroupForecast(){

		}

		~DERGroupForecast(){

		}

		public override void Dispose(){

		}

	}//end DERGroupForecast

}//end namespace DER