///////////////////////////////////////////////////////////
//  DERUnitSymbol.cs
//  Implementation of the Class DERUnitSymbol
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.DER {
	/// <summary>
	/// The units defined for usage in DER related contexts.  This class is a subset
	/// plus possible additions of the UnitSymbol Class in the CIM Domain Package.
	/// </summary>
	public enum DERUnitSymbol : int {

		/// <summary>
		/// Time in seconds.
		/// </summary>
		s = 4,
		/// <summary>
		/// Current in Ampere.
		/// </summary>
		A = 5,
		/// <summary>
		/// Plane angle in degrees.
		/// </summary>
		deg = 9,
		/// <summary>
		/// Relative temperature in degrees Celsius.
		/// In the SI unit system the symbol is ºC. Electric charge is measured in coulomb
		/// that has the unit symbol C. To distinguish degree Celsius form coulomb the
		/// symbol used in the UML is degC. Reason for not using ºC is the special
		/// character º is difficult to manage in software.
		/// </summary>
		degC = 23,
		/// <summary>
		/// Electric potential in Volt (W/A).
		/// </summary>
		V = 29,
		/// <summary>
		/// Electric resistance in ohm (V/A).
		/// </summary>
		ohm = 30,
		/// <summary>
		/// Frequency in Hertz (1/s).
		/// </summary>
		Hz = 33,
		/// <summary>
		/// Real power in Watt (J/s). Electrical power may have real and reactive
		/// components. The real portion of electrical power (I²R or VIcos(phi)), is
		/// expressed in Watts. (See also apparent power and reactive power.)
		/// </summary>
		W = 38,
		/// <summary>
		/// Apparent power in Volt Ampere (See also real power and reactive power.)
		/// </summary>
		VA = 61,
		/// <summary>
		/// Reactive power in Volt Ampere reactive. The “reactive” or “imaginary” component
		/// of electrical power (VIsin(phi)). (See also real power and apparent power).
		/// Note: Different meter designs use different methods to arrive at their results.
		/// Some meters may compute reactive power as an arithmetic value, while others
		/// compute the value vectorially. The data consumer should determine the method in
		/// use and the suitability of the measurement for the intended purpose.
		/// </summary>
		VAr = 63,
		/// <summary>
		/// Volt second (Ws/A).
		/// </summary>
		Vs = 66,
		/// <summary>
		/// Ampere seconds (A·s).
		/// </summary>
		As = 68,
		/// <summary>
		/// Apparent energy in Volt Ampere hours.
		/// </summary>
		VAh = 71,
		/// <summary>
		/// Real energy in Watt hours.
		/// </summary>
		Wh = 72,
		/// <summary>
		/// Reactive energy in Volt Ampere reactive hours.
		/// </summary>
		VArh = 73,
		/// <summary>
		/// Ramp rate in Watt per second.
		/// </summary>
		WPers = 81,
		/// <summary>
		/// Time, hour = 60 min = 3600 s.
		/// </summary>
		h = 84,
		/// <summary>
		/// Time, minute  = 60 s.
		/// </summary>
		min = 85,
		/// <summary>
		/// Quantity power, Q.
		/// </summary>
		Q = 100,
		/// <summary>
		/// Quantity energy, Qh.
		/// </summary>
		Qh = 101,
		/// <summary>
		/// resistivity, Ohm metre, (rho).
		/// </summary>
		ohmm = 102,
		/// <summary>
		/// Ampere-hours, Ampere-hours.
		/// </summary>
		Ah = 106,
		/// <summary>
		/// Energy, British Thermal Unit.
		/// </summary>
		Btu = 132,
		/// <summary>
		/// Power factor, PF, the ratio of the active power to the apparent power. Note:
		/// The sign convention used for power factor will differ between IEC meters and
		/// EEI (ANSI) meters. It is assumed that the data consumers understand the type of
		/// meter being used and agree on the sign convention in use at any given utility.
		/// </summary>
		VPerVA = 153,
		/// <summary>
		/// Energy, Therm.
		/// </summary>
		therm = 169,
		/// <summary>
		/// Volt-hour, Volt hours.
		/// </summary>
		Vh = 280,
		/// <summary>
		/// Active power per current flow, watt per Ampere.
		/// </summary>
		WPerA,
		/// <summary>
		/// Reciprocal of frequency (1/Hz).
		/// </summary>
		onePerHz,
		/// <summary>
		/// Power factor, PF, the ratio of the active power to the apparent power. Note:
		/// The sign convention used for power factor will differ between IEC meters and
		/// EEI (ANSI) meters. It is assumed that the data consumers understand the type of
		/// meter being used and agree on the sign convention in use at any given utility.
		/// </summary>
		VPerVAr,
		/// <summary>
		/// Electric resistance per length in ohm per metre ((V/A)/m).
		/// </summary>
		ohmPerm

	}//end DERUnitSymbol

}//end namespace DER