///////////////////////////////////////////////////////////
//  CrossCompoundTurbineGovernorDynamics.cs
//  Implementation of the Class CrossCompoundTurbineGovernorDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels;
using TC57CIM.IEC61970.Dynamics.StandardModels.SynchronousMachineDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics {
	/// <summary>
	/// Turbine-governor cross-compound function block whose behaviour is described by
	/// reference to a standard model <font color="#0f0f0f">or by definition of a user-
	/// defined model.</font>
	/// </summary>
	public class CrossCompoundTurbineGovernorDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Low-pressure synchronous machine with which this cross-compound turbine
		/// governor is associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.SynchronousMachineDynamics.SynchronousMachineDynamics LowPressureSynchronousMachineDynamics;
		/// <summary>
		/// High-pressure synchronous machine with which this cross-compound turbine
		/// governor is associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.SynchronousMachineDynamics.SynchronousMachineDynamics HighPressureSynchronousMachineDynamics;

		public CrossCompoundTurbineGovernorDynamics(){

		}

		~CrossCompoundTurbineGovernorDynamics(){

		}

		public override void Dispose(){

		}

	}//end CrossCompoundTurbineGovernorDynamics

}//end namespace TurbineGovernorDynamics