///////////////////////////////////////////////////////////
//  GovGAST.cs
//  Implementation of the Class GovGAST
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:58 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics {
	/// <summary>
	/// Single shaft gas turbine.
	/// </summary>
	public class GovGAST : TurbineGovernorDynamics {

		/// <summary>
		/// Ambient temperature load limit (<i>Load Limit</i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU at;
		/// <summary>
		/// Turbine damping factor (<i>Dturb</i>).  Typical value = 0,18.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU dturb;
		/// <summary>
		/// Temperature limiter gain (<i>Kt</i>).  Typical value = 3.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kt;
		/// <summary>
		/// Base for power values (<i>MWbase</i>) (> 0).  Unit = MW.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower mwbase;
		/// <summary>
		/// Permanent droop (<i>R</i>) (>0). Typical value = 0,04.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU r;
		/// <summary>
		/// Governor mechanism time constant (<i>T1</i>) (>= 0).  <i>T1</i> represents the
		/// natural valve positioning time constant of the governor for small disturbances,
		/// as seen when rate limiting is not in effect.  Typical value = 0,5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t1;
		/// <summary>
		/// Turbine power time constant (<i>T2</i>) (>= 0).  <i>T2</i> represents delay due
		/// to internal energy storage of the gas turbine engine. <i>T2</i> can be used to
		/// give a rough approximation to the delay associated with acceleration of the
		/// compressor spool of a multi-shaft engine, or with the compressibility of gas in
		/// the plenum of a free power turbine of an aero-derivative unit, for example.
		/// Typical value = 0,5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t2;
		/// <summary>
		/// Turbine exhaust temperature time constant (<i>T3</i>) (>= 0).  Typical value =
		/// 3.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t3;
		/// <summary>
		/// Maximum turbine power, PU of MWbase (<i>Vmax</i>) (> GovGAST.vmin).  Typical
		/// value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vmax;
		/// <summary>
		/// Minimum turbine power, PU of MWbase (<i>Vmin</i>) (< GovGAST.vmax).  Typical
		/// value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vmin;

		public GovGAST(){

		}

		~GovGAST(){

		}

		public override void Dispose(){

		}

	}//end GovGAST

}//end namespace TurbineGovernorDynamics