///////////////////////////////////////////////////////////
//  GovSteamFV3.cs
//  Implementation of the Class GovSteamFV3
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:00 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics {
	/// <summary>
	/// Simplified GovSteamIEEE1 steam turbine governor with Prmax limit and fast
	/// valving.
	/// </summary>
	public class GovSteamFV3 : TurbineGovernorDynamics {

		/// <summary>
		/// Nonlinear gain valve position point 1 (<i>GV1</i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv1;
		/// <summary>
		/// Nonlinear gain valve position point 2 (<i>GV2</i>).  Typical value = 0,4.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv2;
		/// <summary>
		/// Nonlinear gain valve position point 3 (<i>GV3</i>).  Typical value = 0,5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv3;
		/// <summary>
		/// Nonlinear gain valve position point 4 (<i>GV4</i>).  Typical value = 0,6.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv4;
		/// <summary>
		/// Nonlinear gain valve position point 5 (<i>GV5</i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv5;
		/// <summary>
		/// Nonlinear gain valve position point 6 (<i>GV6</i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU gv6;
		/// <summary>
		/// Governor gain, (reciprocal of droop) (<i>K</i>).  Typical value = 20.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU k;
		/// <summary>
		/// Fraction of turbine power developed after first boiler pass (<i>K1</i>).
		/// Typical value = 0,2.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU k1;
		/// <summary>
		/// Fraction of turbine power developed after second boiler pass (<i>K2</i>).
		/// Typical value = 0,2.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU k2;
		/// <summary>
		/// Fraction of hp turbine power developed after crossover or third boiler pass
		/// (<i>K3</i>). Typical value = 0,6.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU k3;
		/// <summary>
		/// Base for power values (<i>MWbase</i>) (> 0).  Unit = MW.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower mwbase;
		/// <summary>
		/// Nonlinear gain power value point 1 (<i>Pgv1</i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv1;
		/// <summary>
		/// Nonlinear gain power value point 2 (<i>Pgv2</i>).  Typical value = 0,75.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv2;
		/// <summary>
		/// Nonlinear gain power value point 3 (<i>Pgv3</i>).  Typical value = 0,91.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv3;
		/// <summary>
		/// Nonlinear gain power value point 4 (<i>Pgv4</i>).  Typical value = 0,98.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv4;
		/// <summary>
		/// Nonlinear gain power value point 5 (<i>Pgv5</i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv5;
		/// <summary>
		/// Nonlinear gain power value point 6 (<i>Pgv6</i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pgv6;
		/// <summary>
		/// Maximum valve opening, PU of <i>MWbase</i> (<i>Pmax</i>) (> GovSteamFV3.pmin).
		/// Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pmax;
		/// <summary>
		/// Minimum valve opening, PU of <i>MWbase</i> (<i>Pmin</i>) (< GovSteamFV3.pmax).
		/// Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU pmin;
		/// <summary>
		/// Max. pressure in reheater (<i>Prmax</i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU prmax;
		/// <summary>
		/// Governor lead time constant (<i>T1</i>) (>= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t1;
		/// <summary>
		/// Governor lag time constant (<i>T2</i>) (>= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t2;
		/// <summary>
		/// Valve positioner time constant (<i>T3</i>) (> 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t3;
		/// <summary>
		/// Inlet piping/steam bowl time constant (<i>T4</i>) (>= 0).  Typical value = 0,2.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t4;
		/// <summary>
		/// Time constant of second boiler pass (i.e. reheater) (<i>T5</i>) (> 0 if fast
		/// valving is used, otherwise >= 0).  Typical value = 0,5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t5;
		/// <summary>
		/// Time constant of crossover or third boiler pass (<i>T6</i>) (>= 0).  Typical
		/// value = 10.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds t6;
		/// <summary>
		/// Time to close intercept valve (IV) (<i>Ta</i>) (>= 0).  Typical value = 0,97.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds ta;
		/// <summary>
		/// Time until IV starts to reopen (<i>Tb</i>) (>= 0).  Typical value = 0,98.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tb;
		/// <summary>
		/// Time until IV is fully open (<i>Tc</i>) (>= 0).  Typical value = 0,99.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tc;
		/// <summary>
		/// Maximum valve closing velocity (<i>Uc</i>).  Unit = PU / s.  Typical value = -1.
		/// 
		/// </summary>
		public float uc;
		/// <summary>
		/// Maximum valve opening velocity (<i>Uo</i>).  Unit = PU / s.  Typical value = 0,
		/// 1.
		/// </summary>
		public float uo;

		public GovSteamFV3(){

		}

		~GovSteamFV3(){

		}

		public override void Dispose(){

		}

	}//end GovSteamFV3

}//end namespace TurbineGovernorDynamics