///////////////////////////////////////////////////////////
//  GateInputPin.cs
//  Implementation of the Class GateInputPin
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:57 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.InfIEC61970.InfSIPS;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// Input pin for a logical gate. The condition described in the input pin will
	/// give a logical true or false. Result from measurement and calculation are
	/// converted to a true or false.
	/// </summary>
	public class GateInputPin : IdentifiedObject {

		/// <summary>
		/// If true, use the absolute value for compare..
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean absoluteValue;
		/// <summary>
		/// The compare operation.
		/// </summary>
		public AnalogToDigitalLogicKind aDLogicKind;
		/// <summary>
		/// The duration the compare condition need to be present before given a true.
		/// Default is 0 seconds.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds duration;
		/// <summary>
		/// Invert/negate the result of the compare.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean negate;
		/// <summary>
		/// The threshold percentage that should be used for compare with the percentage
		/// change between input value and threshold value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent thresholdPercentage;
		/// <summary>
		/// The threshold value that should be used for compare with the input value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float thresholdValue;

		public GateInputPin(){

		}

		~GateInputPin(){

		}

		public override void Dispose(){

		}

	}//end GateInputPin

}//end namespace InfSIPS