///////////////////////////////////////////////////////////
//  FaultImpedance.cs
//  Implementation of the Class FaultImpedance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:56 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970.Base.Faults {
	/// <summary>
	/// Impedance description for the fault.
	/// </summary>
	public class FaultImpedance {

		/// <summary>
		/// The resistance of the fault between phases and ground.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance rGround;
		/// <summary>
		/// The resistance of the fault between phases.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance rLineToLine;
		/// <summary>
		/// The reactance of the fault between phases and ground.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance xGround;
		/// <summary>
		/// The reactance of the fault between phases.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance xLineToLine;

		public FaultImpedance(){

		}

		~FaultImpedance(){

		}

		public virtual void Dispose(){

		}

	}//end FaultImpedance

}//end namespace Faults