///////////////////////////////////////////////////////////
//  NonConformLoadSchedule.cs
//  Implementation of the Class NonConformLoadSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.LoadModel;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// An active power (Y1-axis) and reactive power (Y2-axis) schedule (curves) versus
	/// time (X-axis) for non-conforming loads, e.g., large industrial load or power
	/// station service (where modelled).
	/// </summary>
	public class NonConformLoadSchedule : SeasonDayTypeSchedule {

		public NonConformLoadSchedule(){

		}

		~NonConformLoadSchedule(){

		}

		public override void Dispose(){

		}

	}//end NonConformLoadSchedule

}//end namespace LoadModel