///////////////////////////////////////////////////////////
//  PowerCutZone.cs
//  Implementation of the Class PowerCutZone
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:14 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Wires;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// An area or zone of the power system which is used for load shedding purposes.
	/// </summary>
	public class PowerCutZone : PowerSystemResource {

		/// <summary>
		/// First level (amount) of load to cut as a percentage of total zone load.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent cutLevel1;
		/// <summary>
		/// Second level (amount) of load to cut as a percentage of total zone load.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent cutLevel2;
		/// <summary>
		/// Energy consumer is assigned to the power cut zone.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.EnergyConsumer EnergyConsumers;

		public PowerCutZone(){

		}

		~PowerCutZone(){

		}

		public override void Dispose(){

		}

	}//end PowerCutZone

}//end namespace LoadModel