///////////////////////////////////////////////////////////
//  SubLoadArea.cs
//  Implementation of the Class SubLoadArea
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.LoadModel;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// The class is the second level in a hierarchical structure for grouping of loads
	/// for the purpose of load flow load scaling.
	/// </summary>
	public class SubLoadArea : EnergyArea {

		/// <summary>
		/// The Loadgroups in the SubLoadArea.
		/// </summary>
		public TC57CIM.IEC61970.Base.LoadModel.LoadGroup LoadGroups;

		public SubLoadArea(){

		}

		~SubLoadArea(){

		}

		public override void Dispose(){

		}

	}//end SubLoadArea

}//end namespace LoadModel