///////////////////////////////////////////////////////////
//  CSCDynamics.cs
//  Implementation of the Class CSCDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.DC;
using TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics {
	/// <summary>
	/// CSC function block whose behaviour is described by reference to a standard
	/// model <font color="#0f0f0f">or by definition of a user-defined model.</font>
	/// </summary>
	public class CSCDynamics : HVDCDynamics {

		/// <summary>
		/// Current source converter to which current source converter dynamics model
		/// applies.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.CsConverter CSConverter;

		public CSCDynamics(){

		}

		~CSCDynamics(){

		}

		public override void Dispose(){

		}

	}//end CSCDynamics

}//end namespace HVDCDynamics