///////////////////////////////////////////////////////////
//  HVDCDynamics.cs
//  Implementation of the Class HVDCDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics {
	/// <summary>
	/// HVDC whose behaviour is described by reference to a standard model <font
	/// color="#0f0f0f">or by definition of a user-defined model.</font>
	/// </summary>
	public class HVDCDynamics : DynamicsFunctionBlock {

		public HVDCDynamics(){

		}

		~HVDCDynamics(){

		}

		public override void Dispose(){

		}

	}//end HVDCDynamics

}//end namespace HVDCDynamics