///////////////////////////////////////////////////////////
//  OilPreservationKind.cs
//  Implementation of the Class OilPreservationKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of oil preservation.
	/// </summary>
	public enum OilPreservationKind : int {

		freeBreathing,
		nitrogenBlanket,
		conservator,
		other

	}//end OilPreservationKind

}//end namespace InfAssetInfo