///////////////////////////////////////////////////////////
//  OldSwitchInfo.cs
//  Implementation of the Class OldSwitchInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Properties of switch assets.
	/// </summary>
	public class OldSwitchInfo : SwitchInfo {

		/// <summary>
		/// The maximum rms voltage that may be applied across an open contact without
		/// breaking down the dielectric properties of the switch in the open position.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage dielectricStrength;
		/// <summary>
		/// True if switch has load breaking capabiity. Unless specified false, this is
		/// always assumed to be true for breakers and reclosers.
		/// </summary>
		public bool loadBreak;
		/// <summary>
		/// The highest value of current the switch can make at the rated voltage under
		/// specified operating conditions without suffering significant deterioration of
		/// its performance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow makingCapacity;
		/// <summary>
		/// The lowest value of current that the switch can make, carry and break in
		/// uninterrupted duty at the rated voltage under specified operating conditions
		/// without suffering significant deterioration of its performance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow minimumCurrent;
		/// <summary>
		/// Number of poles (i.e. of current carrying conductors that are switched).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer poleCount;
		/// <summary>
		/// True if device is capable of being operated by remote control.
		/// </summary>
		public bool remote;
		/// <summary>
		/// The highest value of current the switch can carry in the closed position at the
		/// rated voltage under specified operating conditions without suffering
		/// significant deterioration of its performance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow withstandCurrent;

		public OldSwitchInfo(){

		}

		~OldSwitchInfo(){

		}

		public override void Dispose(){

		}

	}//end OldSwitchInfo

}//end namespace InfAssetInfo