///////////////////////////////////////////////////////////
//  OldTransformerEndInfo.cs
//  Implementation of the Class OldTransformerEndInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.InfIEC61968.InfAssetInfo;
using TC57CIM.IEC61968.AssetInfo;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	public class OldTransformerEndInfo : TransformerEndInfo {

		/// <summary>
		/// Overload rating for 24 hours.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ApparentPower dayOverLoadRating;
		/// <summary>
		/// Overload rating for 1 hour.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ApparentPower hourOverLoadRating;
		/// <summary>
		/// Weight of solid insultation in transformer.
		/// </summary>
		public Mass solidInsulationWeight;
		/// <summary>
		/// Type of insultation used for transformer windings.
		/// </summary>
		public WindingInsulationKind windingInsulationKind;

		public OldTransformerEndInfo(){

		}

		~OldTransformerEndInfo(){

		}

		public override void Dispose(){

		}

	}//end OldTransformerEndInfo

}//end namespace InfAssetInfo