///////////////////////////////////////////////////////////
//  TransformerFunctionKind.cs
//  Implementation of the Class TransformerFunctionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Function of a transformer.
	/// </summary>
	public enum TransformerFunctionKind : int {

		powerTransformer,
		voltageRegulator,
		autotransformer,
		secondaryTransformer,
		other

	}//end TransformerFunctionKind

}//end namespace InfAssetInfo