///////////////////////////////////////////////////////////
//  IncidentHazard.cs
//  Implementation of the Class IncidentHazard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// Hazardous situation associated with an incident. Examples are line down, gas
	/// leak, fire, etc.
	/// </summary>
	public class IncidentHazard : Hazard {

		public IncidentHazard(){

		}

		~IncidentHazard(){

		}

		public override void Dispose(){

		}

	}//end IncidentHazard

}//end namespace Customers