///////////////////////////////////////////////////////////
//  TroubleSymptomsTransformerKind.cs
//  Implementation of the Class TroubleSymptomsTransformerKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of items that define the transformer problem.
	/// </summary>
	public enum TroubleSymptomsTransformerKind : int {

		ok,
		burning,
		other

	}//end TroubleSymptomsTransformerKind

}//end namespace Customers