///////////////////////////////////////////////////////////
//  TroubleSymptomsExtentKind.cs
//  Implementation of the Class TroubleSymptomsExtentKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The enumerated values that define the extent of the problem.
	/// </summary>
	public enum TroubleSymptomsExtentKind : int {

		singleCustomer,
		ok,
		neighbour,
		other,
		entireNeighbourhood

	}//end TroubleSymptomsExtentKind

}//end namespace Customers