///////////////////////////////////////////////////////////
//  ReportingGroup.cs
//  Implementation of the Class ReportingGroup
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// A reporting group is used for various ad-hoc groupings used for reporting.
	/// </summary>
	public class ReportingGroup : IdentifiedObject {

		/// <summary>
		/// Power system resources which belong to this reporting group.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.PowerSystemResource PowerSystemResource;

		public ReportingGroup(){

		}

		~ReportingGroup(){

		}

		public override void Dispose(){

		}

	}//end ReportingGroup

}//end namespace Core