///////////////////////////////////////////////////////////
//  SubGeographicalRegion.cs
//  Implementation of the Class SubGeographicalRegion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Wires;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// A subset of a geographical region of a power system network model.
	/// </summary>
	public class SubGeographicalRegion : IdentifiedObject {

		/// <summary>
		/// The lines within the sub-geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.Line Lines;
		/// <summary>
		/// The substations in this sub-geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.Substation Substations;

		public SubGeographicalRegion(){

		}

		~SubGeographicalRegion(){

		}

		public override void Dispose(){

		}

	}//end SubGeographicalRegion

}//end namespace Core