///////////////////////////////////////////////////////////
//  BankAccount.cs
//  Implementation of the Class BankAccount
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.InfIEC61968.InfCommon;
using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// Bank account.
	/// </summary>
	public class BankAccount : Document {

		/// <summary>
		/// Account reference number.
		/// </summary>
		public string accountNumber;
		/// <summary>
		/// Bank that provides this BankAccount.
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfCommon.Bank Bank;

		public BankAccount(){

		}

		~BankAccount(){

		}

		public override void Dispose(){

		}

	}//end BankAccount

}//end namespace InfCommon