///////////////////////////////////////////////////////////
//  BusinessRole.cs
//  Implementation of the Class BusinessRole
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// A business role that this organisation plays. A single organisation typically
	/// performs many functions, each one described as a role.
	/// </summary>
	public class BusinessRole : OrganisationRole {

		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// Classification by utility's corporate standards and practices.
		/// </summary>
		public string type;

		public BusinessRole(){

		}

		~BusinessRole(){

		}

		public override void Dispose(){

		}

	}//end BusinessRole

}//end namespace InfCommon