///////////////////////////////////////////////////////////
//  IEC61970CIMVersion.cs
//  Implementation of the Class IEC61970CIMVersion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:04 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61970 {
	/// <summary>
	/// This is the IEC 61970 CIM version number assigned to this UML model.
	/// </summary>
	public class IEC61970CIMVersion {

		/// <summary>
		/// Form is YYYY-MM-DD for example for January 5, 2009 it is 2009-01-05.
		/// </summary>
		public static readonly System.DateTime Date = new System.DateTime(2020,8,24);
		/// <summary>
		/// Form is IEC61970CIMXXvYY where XX is the major CIM package version and the YY
		/// is the minor version. For example IEC61970CIM13v18.
		/// </summary>
		public static readonly string version = "IEC61970CIM17v40";

		public IEC61970CIMVersion(){

		}

		~IEC61970CIMVersion(){

		}

		public virtual void Dispose(){

		}

	}//end IEC61970CIMVersion

}//end namespace IEC61970