///////////////////////////////////////////////////////////
//  BusNameMarker.cs
//  Implementation of the Class BusNameMarker
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:42 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.Base.Topology;
namespace TC57CIM.IEC61970.Base.Topology {
	/// <summary>
	/// Used to apply user standard names to TopologicalNodes. Associated with one or
	/// more terminals that are normally connected with the bus name.    The associated
	/// terminals are normally connected by non-retained switches. For a ring bus
	/// station configuration, all BusbarSection terminals in the ring are typically
	/// associated.   For a breaker and a half scheme, both BusbarSections would
	/// normally be associated.  For a ring bus, all BusbarSections would normally be
	/// associated.  For a "straight" busbar configuration, normally only the main
	/// terminal at the BusbarSection would be associated.
	/// </summary>
	public class BusNameMarker : IdentifiedObject {

		/// <summary>
		/// Priority of bus name marker for use as topology bus name.  Use 0 for do not
		/// care.  Use 1 for highest priority.  Use 2 as priority is less than 1 and so on.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer priority;
		/// <summary>
		/// The reporting group to which this bus name marker belongs.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.ReportingGroup ReportingGroup;
		/// <summary>
		/// The terminals associated with this bus name marker.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.ACDCTerminal Terminal;
		/// <summary>
		/// A user defined topological node that was originally defined in a planning model
		/// not yet having topology described by ConnectivityNodes. Once ConnectivityNodes
		/// has been created they may linked to user defined ToplogicalNdes using
		/// BusNameMarkers.
		/// </summary>
		public TC57CIM.IEC61970.Base.Topology.TopologicalNode TopologicalNode;

		public BusNameMarker(){

		}

		~BusNameMarker(){

		}

		public override void Dispose(){

		}

	}//end BusNameMarker

}//end namespace Topology