///////////////////////////////////////////////////////////
//  ChangeSet.cs
//  Implementation of the Class ChangeSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:42 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet;
namespace TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet {
	/// <summary>
	/// Describes a set of changes that can be applied in different situations.   A
	/// given registered target object  MRID may only be referenced once by the
	/// contained change set members.
	/// </summary>
	public class ChangeSet : DataSet {

		public ChangeSet(){

		}

		~ChangeSet(){

		}

		public override void Dispose(){

		}

	}//end ChangeSet

}//end namespace GenericDataSet