///////////////////////////////////////////////////////////
//  ObjectCreation.cs
//  Implementation of the Class ObjectCreation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet;
namespace TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet {
	/// <summary>
	/// An object is to be created in the context.
	/// </summary>
	public class ObjectCreation : ChangeSetMember {

		public ObjectCreation(){

		}

		~ObjectCreation(){

		}

		public override void Dispose(){

		}

	}//end ObjectCreation

}//end namespace GenericDataSet