///////////////////////////////////////////////////////////
//  PowerSystemStabilizerDynamics.cs
//  Implementation of the Class PowerSystemStabilizerDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels;
using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
using TC57CIM.IEC61970.Dynamics.StandardInterconnections;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.PowerSystemStabilizerDynamics {
	/// <summary>
	/// Power system stabilizer function block whose behaviour is described by
	/// reference to a standard model <font color="#0f0f0f">or by definition of a user-
	/// defined model.</font>
	/// </summary>
	public class PowerSystemStabilizerDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Excitation system model with which this power system stabilizer model is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics ExcitationSystemDynamics;
		/// <summary>
		/// Remote input signal used by this power system stabilizer model.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal RemoteInputSignal;

		public PowerSystemStabilizerDynamics(){

		}

		~PowerSystemStabilizerDynamics(){

		}

		public override void Dispose(){

		}

	}//end PowerSystemStabilizerDynamics

}//end namespace PowerSystemStabilizerDynamics