///////////////////////////////////////////////////////////
//  IncrementalDatasetArgDescription.cs
//  Implementation of the Class IncrementalDatasetArgDescription
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:04 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations {
	public class IncrementalDatasetArgDescription : ModelOperationArgDescription {

		public IncrementalDatasetArgDescription(){

		}

		~IncrementalDatasetArgDescription(){

		}

		public override void Dispose(){

		}

	}//end IncrementalDatasetArgDescription

}//end namespace ModelOperations