///////////////////////////////////////////////////////////
//  ErpAccountKind.cs
//  Implementation of the Class ErpAccountKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of ERP account.
	/// </summary>
	public enum ErpAccountKind : int {

		normal,
		reversal,
		statistical,
		estimate

	}//end ErpAccountKind

}//end namespace InfERPSupport