///////////////////////////////////////////////////////////
//  ErpBOM.cs
//  Implementation of the Class ErpBOM
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.InfIEC61968.InfERPSupport;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Information that generally describes the Bill of Material Structure and its
	/// contents for a utility.
	/// 
	/// This is used by ERP systems to transfer Bill of Material information between
	/// two business applications.
	/// </summary>
	public class ErpBOM : ErpDocument {

		public ErpBOM(){

		}

		~ErpBOM(){

		}

		public override void Dispose(){

		}

	}//end ErpBOM

}//end namespace InfERPSupport