///////////////////////////////////////////////////////////
//  ErpIdentifiedObject.cs
//  Implementation of the Class ErpIdentifiedObject
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Shadow class for IdentifiedObject, to isolate subclassing from this package. If
	/// any subclass gets normative and needs inheritance, it will inherit directly
	/// from IdentifiedObject.
	/// </summary>
	public class ErpIdentifiedObject : IdentifiedObject {

		public ErpIdentifiedObject(){

		}

		~ErpIdentifiedObject(){

		}

		public override void Dispose(){

		}

	}//end ErpIdentifiedObject

}//end namespace InfERPSupport