///////////////////////////////////////////////////////////
//  ErpInvoiceLineItemKind.cs
//  Implementation of the Class ErpInvoiceLineItemKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of invoice line item.
	/// </summary>
	public enum ErpInvoiceLineItemKind : int {

		initial,
		recalculation,
		other

	}//end ErpInvoiceLineItemKind

}//end namespace InfERPSupport