///////////////////////////////////////////////////////////
//  ErpIssueInventory.cs
//  Implementation of the Class ErpIssueInventory
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61968.InfIEC61968.InfERPSupport;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Can be used to request an application to process an issue or request
	/// information about an issue.
	/// </summary>
	public class ErpIssueInventory : ErpIdentifiedObject {

		public TC57CIM.IEC61968.Common.Status status;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.TypeMaterial TypeMaterial;
		public TC57CIM.IEC61968.AssetInfo.Assets.CatalogAssetType TypeAsset;

		public ErpIssueInventory(){

		}

		~ErpIssueInventory(){

		}

		public override void Dispose(){

		}

	}//end ErpIssueInventory

}//end namespace InfERPSupport