///////////////////////////////////////////////////////////
//  ErpPOLineItem.cs
//  Implementation of the Class ErpPOLineItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.InfIEC61968.InfERPSupport;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Of an ErpPurchaseOrder, this is an individually ordered item or product along
	/// with the quantity, price and other descriptive information.
	/// </summary>
	public class ErpPOLineItem : ErpDocument {

		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPurchaseOrder ErpPurchaseOrder;

		public ErpPOLineItem(){

		}

		~ErpPOLineItem(){

		}

		public override void Dispose(){

		}

	}//end ErpPOLineItem

}//end namespace InfERPSupport