///////////////////////////////////////////////////////////
//  ErpReqLineItem.cs
//  Implementation of the Class ErpReqLineItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfERPSupport;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Information that describes a requested item and its attributes.
	/// </summary>
	public class ErpReqLineItem : ErpIdentifiedObject {

		public TC57CIM.IEC61970.Base.Domain.String code;
		/// <summary>
		/// Cost of material.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money cost;
		public TC57CIM.IEC61970.Base.Domain.Date deliveryDate;
		/// <summary>
		/// Quantity of item requisitioned.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer quantity;
		public TC57CIM.IEC61968.Common.Status status;
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpRequisition ErpRequisition;
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPOLineItem ErpPOLineItem;

		public ErpReqLineItem(){

		}

		~ErpReqLineItem(){

		}

		public override void Dispose(){

		}

	}//end ErpReqLineItem

}//end namespace InfERPSupport