///////////////////////////////////////////////////////////
//  InternalLocation.cs
//  Implementation of the Class InternalLocation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Work;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Description of location internal to a building.
	/// </summary>
	public class InternalLocation : WorkLocation {

		/// <summary>
		/// Name of building where location is.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String buildingName;
		/// <summary>
		/// Number of building where location is.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String buildingNumber;
		/// <summary>
		/// Floor of location.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer floor;
		/// <summary>
		/// Room number of location.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String roomNumber;

		public InternalLocation(){

		}

		~InternalLocation(){

		}

		public override void Dispose(){

		}

	}//end InternalLocation

}//end namespace Work