///////////////////////////////////////////////////////////
//  TransformerRepairItemKind.cs
//  Implementation of the Class TransformerRepairItemKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Transformer components and problem areas which can be the focus of a repair
	/// work task.
	/// WorkTimeScheduleKind enumeration
	/// Kind of work schedule.
	/// </summary>
	public enum TransformerRepairItemKind : int {

	}//end TransformerRepairItemKind

}//end namespace Work