///////////////////////////////////////////////////////////
//  WorkLocation.cs
//  Implementation of the Class WorkLocation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Information about a particular location for various forms of work.
	/// </summary>
	public class WorkLocation : Location {

		public TC57CIM.IEC61968.InfIEC61968.InfWork.OneCallRequest OneCallRequest;

		public WorkLocation(){

		}

		~WorkLocation(){

		}

		public override void Dispose(){

		}

	}//end WorkLocation

}//end namespace Work