///////////////////////////////////////////////////////////
//  WorkTaskKind.cs
//  Implementation of the Class WorkTaskKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Kinds of work tasks.
	/// </summary>
	public enum WorkTaskKind : int {

		/// <summary>
		/// Work task deals with installation of assets.
		/// </summary>
		install,
		/// <summary>
		/// Work task deals with removal of assets.
		/// </summary>
		remove,
		/// <summary>
		/// Work task deals with exchange of assets.
		/// </summary>
		exchange,
		/// <summary>
		/// Work task deals with investigation about assets.
		/// </summary>
		investigate

	}//end WorkTaskKind

}//end namespace Work