///////////////////////////////////////////////////////////
//  WorkTimeSchedule.cs
//  Implementation of the Class WorkTimeSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Work;
using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Time schedule specific to work.
	/// </summary>
	public class WorkTimeSchedule : TimeSchedule {

		/// <summary>
		/// Kind of this work schedule.
		/// </summary>
		public WorkTimeScheduleKind kind;

		public WorkTimeSchedule(){

		}

		~WorkTimeSchedule(){

		}

		public override void Dispose(){

		}

	}//end WorkTimeSchedule

}//end namespace Work