///////////////////////////////////////////////////////////
//  EnergyConnection.cs
//  Implementation of the Class EnergyConnection
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:49 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.InfIEC61970.EnergyArea;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A connection of energy generation or consumption on the power system model.
	/// </summary>
	public class EnergyConnection : ConductingEquipment {

		public TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyComponent m_EnergyComponent;

		public EnergyConnection(){

		}

		~EnergyConnection(){

		}

		public override void Dispose(){

		}

	}//end EnergyConnection

}//end namespace Wires