///////////////////////////////////////////////////////////
//  GroundingImpedance.cs
//  Implementation of the Class GroundingImpedance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:00 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Wires;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A fixed impedance device used for grounding.
	/// </summary>
	public class GroundingImpedance : EarthFaultCompensator {

		/// <summary>
		/// Reactance of device.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance x;

		public GroundingImpedance(){

		}

		~GroundingImpedance(){

		}

		public override void Dispose(){

		}

	}//end GroundingImpedance

}//end namespace Wires