///////////////////////////////////////////////////////////
//  NonlinearShuntCompensator.cs
//  Implementation of the Class NonlinearShuntCompensator
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Wires;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A non linear shunt compensator has bank or section admittance values that
	/// differ. The attributes g, b, g0 and b0 of the associated
	/// NonlinearShuntCompensatorPoint describe the total conductance and admittance of
	/// a NonlinearShuntCompensatorPoint at a section number specified by
	/// NonlinearShuntCompensatorPoint.sectionNumber.
	/// </summary>
	public class NonlinearShuntCompensator : ShuntCompensator {

		/// <summary>
		/// All points of the non-linear shunt compensator.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.NonlinearShuntCompensatorPoint NonlinearShuntCompensatorPoints;

		public NonlinearShuntCompensator(){

		}

		~NonlinearShuntCompensator(){

		}

		public override void Dispose(){

		}

	}//end NonlinearShuntCompensator

}//end namespace Wires