///////////////////////////////////////////////////////////
//  PhaseShuntConnectionKind.cs
//  Implementation of the Class PhaseShuntConnectionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// The configuration of phase connections for a single terminal device such as a
	/// load or capacitor.
	/// </summary>
	public enum PhaseShuntConnectionKind : int {

		/// <summary>
		/// Delta connection.
		/// </summary>
		D = 1,
		/// <summary>
		/// Wye connection.
		/// </summary>
		Y = 2,
		/// <summary>
		/// Wye, with neutral brought out for grounding.
		/// </summary>
		Yn = 3,
		/// <summary>
		/// Independent winding, for single-phase connections.
		/// </summary>
		I = 4,
		/// <summary>
		/// Ground connection; use when explicit connection to ground needs to be expressed
		/// in combination with the phase code, such as for electrical wire/cable or for
		/// meters.
		/// </summary>
		G = 5

	}//end PhaseShuntConnectionKind

}//end namespace Wires