///////////////////////////////////////////////////////////
//  StaticVarCompensator.cs
//  Implementation of the Class StaticVarCompensator
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:22 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Wires;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A facility for providing variable and controllable shunt reactive power. The
	/// SVC typically consists of a stepdown transformer, filter, thyristor-controlled
	/// reactor, and thyristor-switched capacitor arms.
	/// 
	/// The SVC may operate in fixed MVar output mode or in voltage control mode. When
	/// in voltage control mode, the output of the SVC will be proportional to the
	/// deviation of voltage at the controlled bus from the voltage setpoint.  The SVC
	/// characteristic slope defines the proportion.  If the voltage at the controlled
	/// bus is equal to the voltage setpoint, the SVC MVar output is zero.
	/// </summary>
	public class StaticVarCompensator : RegulatingCondEq {

		/// <summary>
		/// Capacitive reactance at maximum capacitive reactive power.  Shall always be
		/// positive.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance capacitiveRating;
		/// <summary>
		/// Inductive reactance at maximum inductive reactive power.  Shall always be
		/// negative.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance inductiveRating;
		/// <summary>
		/// Reactive power injection. Load sign convention is used, i.e. positive sign
		/// means flow out from a node.
		/// Starting value for a steady state solution.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ReactivePower q;
		/// <summary>
		/// The characteristics slope of an SVC defines how the reactive power output
		/// changes in proportion to the difference between the regulated bus voltage and
		/// the voltage setpoint.
		/// The attribute shall be a positive value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.VoltagePerReactivePower slope;
		/// <summary>
		/// SVC control mode.
		/// </summary>
		public SVCControlMode sVCControlMode;
		/// <summary>
		/// The reactive power output of the SVC is proportional to the difference between
		/// the voltage at the regulated bus and the voltage setpoint.  When the regulated
		/// bus voltage is equal to the voltage setpoint, the reactive power output is zero.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage voltageSetPoint;

		public StaticVarCompensator(){

		}

		~StaticVarCompensator(){

		}

		public override void Dispose(){

		}

	}//end StaticVarCompensator

}//end namespace Wires