///////////////////////////////////////////////////////////
//  TransformerMeshImpedance.cs
//  Implementation of the Class TransformerMeshImpedance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:26 AM
//  Original author: LOO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Wires;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Transformer mesh impedance (Delta-model) between transformer ends.
	/// The typical case is that this class describes the impedance between two
	/// transformer ends pair-wise, i.e. the cardinalities at both transformer end
	/// associations are 1. However, in cases where two or more transformer ends are
	/// modelled the cardinalities are larger than 1.
	/// </summary>
	public class TransformerMeshImpedance : IdentifiedObject {

		/// <summary>
		/// Resistance between the 'from' and the 'to' end, seen from the 'from' end.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance r;
		/// <summary>
		/// Zero-sequence resistance between the 'from' and the 'to' end, seen from the
		/// 'from' end.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Resistance r0;
		/// <summary>
		/// Reactance between the 'from' and the 'to' end, seen from the 'from' end.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance x;
		/// <summary>
		/// Zero-sequence reactance between the 'from' and the 'to' end, seen from the
		/// 'from' end.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Reactance x0;
		/// <summary>
		/// All transformer ends this mesh impedance is connected to.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.TransformerEnd ToTransformerEnd;
		/// <summary>
		/// From end this mesh impedance is connected to. It determines the voltage
		/// reference.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.TransformerEnd FromTransformerEnd;

		public TransformerMeshImpedance(){

		}

		~TransformerMeshImpedance(){

		}

		public override void Dispose(){

		}

	}//end TransformerMeshImpedance

}//end namespace Wires