///////////////////////////////////////////////////////////
//  ExcAVR1.cs
//  Implementation of the Class ExcAVR1
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:52 AM
//  Original author: pcha006
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics {
	/// <summary>
	/// Italian excitation system corresponding to IEEE (1968) type 1 model. It
	/// represents an exciter dynamo and electromechanical regulator.
	/// </summary>
	public class ExcAVR1 : ExcitationSystemDynamics {

		/// <summary>
		/// Field voltage value 1 (<i>E</i><i><sub>1</sub></i>).  Typical value = 4.18.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU e1;
		/// <summary>
		/// Field voltage value 2 (<i>E</i><i><sub>2</sub></i>).  Typical value = 3,14.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU e2;
		/// <summary>
		/// AVR gain (<i>K</i><i><sub>A</sub></i>).  Typical value = 500.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float ka;
		/// <summary>
		/// Rate feedback gain (<i>K</i><i><sub>F</sub></i>).  Typical value = 0,12.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float kf;
		/// <summary>
		/// Saturation factor at <i>E</i><i><sub>1</sub></i>
		/// (<i>S[E</i><i><sub>1</sub></i><i>]</i>).  Typical value = 0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float se1;
		/// <summary>
		/// Saturation factor at <i>E</i><i><sub>2</sub></i>
		/// (<i>S[E</i><i><sub>2</sub></i><i>]</i>).  Typical value = 0,03.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float se2;
		/// <summary>
		/// AVR time constant (<i>T</i><i><sub>A</sub></i>) (>= 0).  Typical value = 0,2.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds ta;
		/// <summary>
		/// AVR time constant (<i>T</i><i><sub>B</sub></i>) (>= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tb;
		/// <summary>
		/// Exciter time constant (<i>T</i><i><sub>E</sub></i>) (>= 0).  Typical value = 1.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds te;
		/// <summary>
		/// Rate feedback time constant (<i>T</i><i><sub>F</sub></i>) (>= 0).  Typical
		/// value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tf;
		/// <summary>
		/// Minimum AVR output (<i>V</i><i><sub>RMN</sub></i>).  Typical value = -6.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmn;
		/// <summary>
		/// Maximum AVR output (<i>V</i><i><sub>RMX</sub></i>).  Typical value = 7.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmx;

		public ExcAVR1(){

		}

		~ExcAVR1(){

		}

		public override void Dispose(){

		}

	}//end ExcAVR1

}//end namespace ExcitationSystemDynamics