///////////////////////////////////////////////////////////
//  ExcDC3A.cs
//  Implementation of the Class ExcDC3A
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:52 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics {
	/// <summary>
	/// Modified IEEE DC3A direct current commutator exciter with speed input, and
	/// deadband.  DC old type 4.
	/// </summary>
	public class ExcDC3A : ExcitationSystemDynamics {

		/// <summary>
		/// Exciter voltage at which exciter saturation is defined
		/// (<i>Efd</i><i><sub>1</sub></i>) (> 0).  Typical value = 2,6.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU efd1;
		/// <summary>
		/// Exciter voltage at which exciter saturation is defined
		/// (<i>Efd</i><i><sub>2</sub></i>) (> 0).  Typical value = 3,45.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU efd2;
		/// <summary>
		/// (<i>Efdlim</i>).
		/// true = exciter output limiter is active
		/// false = exciter output limiter not active.
		/// Typical value = true.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean efdlim;
		/// <summary>
		/// Maximum voltage exciter output limiter (<i>Efdmax</i>) (> ExcDC3A.efdmin).
		/// Typical value = 99.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU efdmax;
		/// <summary>
		/// Minimum voltage exciter output limiter (<i>Efdmin</i>) (< ExcDC3A.efdmax).
		/// Typical value = -99.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU efdmin;
		/// <summary>
		/// (<i>exclim</i>).  IEEE standard is ambiguous about lower limit on exciter
		/// output.
		/// true = a lower limit of zero is applied to integrator output
		/// false = a lower limit of zero not applied to integrator output.
		/// Typical value = true.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean exclim;
		/// <summary>
		/// Exciter constant related to self-excited field (<i>Ke</i>).  Typical value = 1.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU ke;
		/// <summary>
		/// Deadband (<i>Kr</i>).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kr;
		/// <summary>
		/// Coefficient to allow different usage of the model-speed coefficient (<i>Ks</i>).
		///  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU ks;
		/// <summary>
		/// Fast raise/lower contact setting (<i>Kv</i>) (> 0).  Typical value = 0,05.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kv;
		/// <summary>
		/// Exciter saturation function value at the corresponding exciter voltage,
		/// <i>Efd</i><i><sub>1</sub></i> (<i>Se[Efd</i><i><sub>1</sub></i><i>]</i>) (>= 0).
		///  Typical value = 0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float seefd1;
		/// <summary>
		/// Exciter saturation function value at the corresponding exciter voltage,
		/// <i>Efd</i><i><sub>2</sub></i> (<i>Se[Efd</i><i><sub>2</sub></i><i>]</i>) (>= 0).
		///  Typical value = 0,35.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float seefd2;
		/// <summary>
		/// Exciter time constant, integration rate associated with exciter control
		/// (<i>Te</i>) (> 0).  Typical value = 1,83.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds te;
		/// <summary>
		/// Rheostat travel time (<i>Trh</i>) (> 0).  Typical value = 20.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds trh;
		/// <summary>
		/// Maximum voltage regulator output (<i>Vrmax</i>) (> 0).  Typical value = 5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmax;
		/// <summary>
		/// Minimum voltage regulator output (<i>Vrmin</i>) (<= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmin;

		public ExcDC3A(){

		}

		~ExcDC3A(){

		}

		public override void Dispose(){

		}

	}//end ExcDC3A

}//end namespace ExcitationSystemDynamics