///////////////////////////////////////////////////////////
//  ExcIEEEST6B.cs
//  Implementation of the Class ExcIEEEST6B
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:54 AM
//  Original author: pcha006
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics {
	/// <summary>
	/// IEEE 421.5-2005 type ST6B model. This model consists of a PI voltage regulator
	/// with an inner loop field voltage regulator and pre-control. The field voltage
	/// regulator implements a proportional control. The pre-control and the delay in
	/// the feedback circuit increase the dynamic response.
	/// Reference: IEEE 421.5-2005, 7.6.
	/// </summary>
	public class ExcIEEEST6B : ExcitationSystemDynamics {

		/// <summary>
		/// Exciter output current limit reference (<i>I</i><i><sub>LR</sub></i>) (> 0).
		/// Typical value = 4,164.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU ilr;
		/// <summary>
		/// Exciter output current limit adjustment (<i>K</i><i><sub>CI</sub></i>) (> 0).
		/// Typical value = 1,0577.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kci;
		/// <summary>
		/// Pre-control gain constant of the inner loop field regulator
		/// (<i>K</i><i><sub>FF</sub></i>). Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kff;
		/// <summary>
		/// Feedback gain constant of the inner loop field regulator
		/// (<i>K</i><i><sub>G</sub></i>) (>= 0).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kg;
		/// <summary>
		/// Voltage regulator integral gain (<i>K</i><i><sub>IA</sub></i>) (> 0).  Typical
		/// value = 45,094.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kia;
		/// <summary>
		/// Exciter output current limiter gain (<i>K</i><i><sub>LR</sub></i>) (> 0).
		/// Typical value = 17,33.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU klr;
		/// <summary>
		/// Forward gain constant of the inner loop field regulator
		/// (<i>K</i><i><sub>M</sub></i>).  Typical value = 1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU km;
		/// <summary>
		/// Voltage regulator proportional gain (<u>K</u><u><sub>PA</sub></u>) (> 0).
		/// Typical value = 18,038.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kpa;
		/// <summary>
		/// OEL input selector (<i>OELin</i>). Typical value = noOELinput.
		/// </summary>
		public ExcST6BOELselectorKind oelin;
		/// <summary>
		/// Feedback time constant of inner loop field voltage regulator
		/// (<i>T</i><i><sub>G</sub></i>) (>= 0). Typical value = 0,02.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tg;
		/// <summary>
		/// Maximum voltage regulator output (V<i><sub>AMAX</sub></i>) (> 0).  Typical
		/// value = 4,81.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vamax;
		/// <summary>
		/// Minimum voltage regulator output (<i>V</i><i><sub>AMIN</sub></i>) (< 0).
		/// Typical value = -3,85.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vamin;
		/// <summary>
		/// Maximum voltage regulator output (<i>V</i><i><sub>RMAX</sub></i>) (> 0).
		/// Typical value = 4,81.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmax;
		/// <summary>
		/// Minimum voltage regulator output (<i>V</i><i><sub>RMIN</sub></i>) (< 0).
		/// Typical value = -3,85.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vrmin;

		public ExcIEEEST6B(){

		}

		~ExcIEEEST6B(){

		}

		public override void Dispose(){

		}

	}//end ExcIEEEST6B

}//end namespace ExcitationSystemDynamics