///////////////////////////////////////////////////////////
//  WindContPType4bIEC.cs
//  Implementation of the Class WindContPType4bIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:30 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// P control model type 4B.
	/// Reference: IEC 61400-27-1:2015, 5.6.5.6.
	/// </summary>
	public class WindContPType4bIEC : IdentifiedObject {

		/// <summary>
		/// Maximum wind turbine power ramp rate (<i>dp</i><i><sub>maxp4B</sub></i>). It is
		/// a project-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU dpmaxp4b;
		/// <summary>
		/// Time constant in aerodynamic power response (<i>T</i><i><sub>paero</sub></i>)
		/// (>= 0). It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tpaero;
		/// <summary>
		/// Time constant in power order lag (<i>T</i><i><sub>pordp4B</sub></i>) (>= 0). It
		/// is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tpordp4b;
		/// <summary>
		/// Voltage measurement filter time constant (<i>T</i><i><sub>ufiltp4B</sub></i>)
		/// (>= 0). It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tufiltp4b;
		/// <summary>
		/// Wind turbine type 4B model with which this wind control P type 4B model is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType4bIEC WindTurbineType4bIEC;

		public WindContPType4bIEC(){

		}

		~WindContPType4bIEC(){

		}

		public override void Dispose(){

		}

	}//end WindContPType4bIEC

}//end namespace WindDynamics