///////////////////////////////////////////////////////////
//  WindContPType4aIEC.cs
//  Implementation of the Class WindContPType4aIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:30 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// P control model type 4A.
	/// Reference: IEC 61400-27-1:2015, 5.6.5.5.
	/// </summary>
	public class WindContPType4aIEC : IdentifiedObject {

		/// <summary>
		/// Maximum wind turbine power ramp rate (<i>dp</i><i><sub>maxp4A</sub></i>). It is
		/// a project-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU dpmaxp4a;
		/// <summary>
		/// Time constant in power order lag (<i>T</i><i><sub>pordp4A</sub></i>) (>= 0). It
		/// is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tpordp4a;
		/// <summary>
		/// Voltage measurement filter time constant (<i>T</i><i><sub>ufiltp4A</sub></i>)
		/// (>= 0). It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tufiltp4a;
		/// <summary>
		/// Wind turbine type 4A model with which this wind control P type 4A model is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType4aIEC WindTurbineType4aIEC;

		public WindContPType4aIEC(){

		}

		~WindContPType4aIEC(){

		}

		public override void Dispose(){

		}

	}//end WindContPType4aIEC

}//end namespace WindDynamics