///////////////////////////////////////////////////////////
//  WindTurbineType4bIEC.cs
//  Implementation of the Class WindTurbineType4bIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:33 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Wind turbine IEC type 4B.
	/// Reference: IEC 61400-27-1:2015, 5.5.5.3.
	/// </summary>
	public class WindTurbineType4bIEC : WindTurbineType4IEC {

		public WindTurbineType4bIEC(){

		}

		~WindTurbineType4bIEC(){

		}

		public override void Dispose(){

		}

	}//end WindTurbineType4bIEC

}//end namespace WindDynamics