///////////////////////////////////////////////////////////
//  WindMechIEC.cs
//  Implementation of the Class WindMechIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:31 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Two mass model.
	/// Reference: IEC 61400-27-1:2015, 5.6.2.1.
	/// </summary>
	public class WindMechIEC : IdentifiedObject {

		/// <summary>
		/// Drive train damping (<i>c</i><i><sub>drt</sub></i><i>)</i>. It is a type-
		/// dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU cdrt;
		/// <summary>
		/// Inertia constant of generator (<i>H</i><i><sub>gen</sub></i>) (>= 0). It is a
		/// type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds hgen;
		/// <summary>
		/// Inertia constant of wind turbine rotor (<i>H</i><i><sub>WTR</sub></i>) (>= 0).
		/// It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds hwtr;
		/// <summary>
		/// Drive train stiffness (<i>k</i><i><sub>drt</sub></i>). It is a type-dependent
		/// parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU kdrt;
		/// <summary>
		/// Wind turbine type 4B model with which this wind mechanical model is associated.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType4bIEC WindTurbineType4bIEC;
		/// <summary>
		/// Wind turbine type 3 model with which this wind mechanical model is associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType3IEC WindTurbineType3IEC;
		/// <summary>
		/// Wind generator type 1 or type 2 model with which this wind mechanical model is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType1or2IEC WindTurbineType1or2IEC;

		public WindMechIEC(){

		}

		~WindMechIEC(){

		}

		public override void Dispose(){

		}

	}//end WindMechIEC

}//end namespace WindDynamics