///////////////////////////////////////////////////////////
//  WindTurbineType4aIEC.cs
//  Implementation of the Class WindTurbineType4aIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:33 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Wind turbine IEC type 4A.
	/// Reference: IEC 61400-27-1:2015, 5.5.5.2.
	/// </summary>
	public class WindTurbineType4aIEC : WindTurbineType4IEC {

		public WindTurbineType4aIEC(){

		}

		~WindTurbineType4aIEC(){

		}

		public override void Dispose(){

		}

	}//end WindTurbineType4aIEC

}//end namespace WindDynamics