///////////////////////////////////////////////////////////
//  WindTurbineType3IEC.cs
//  Implementation of the Class WindTurbineType3IEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:32 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Parent class supporting relationships to IEC wind turbines type 3 including
	/// their control models.
	/// </summary>
	public class WindTurbineType3IEC : WindTurbineType3or4IEC {

		public WindTurbineType3IEC(){

		}

		~WindTurbineType3IEC(){

		}

		public override void Dispose(){

		}

	}//end WindTurbineType3IEC

}//end namespace WindDynamics