///////////////////////////////////////////////////////////
//  BilateralExchangeAgreement.cs
//  Implementation of the Class BilateralExchangeAgreement
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61970.Base.ICCPConfiguration;
namespace TC57CIM.IEC61970.Base.ICCPConfiguration {
	/// <summary>
	/// This is the representation of the information exchange agreement between peers.
	/// 
	/// </summary>
	public class BilateralExchangeAgreement : IdentifiedObject {

		/// <summary>
		/// Subscriber of information from a remote peer.
		/// </summary>
		public TC57CIM.IEC61970.Base.ICCPConfiguration.BilateralExchangeActor Consumer;

		public BilateralExchangeAgreement(){

		}

		~BilateralExchangeAgreement(){

		}

		public override void Dispose(){

		}

	}//end BilateralExchangeAgreement

}//end namespace ICCPConfiguration