///////////////////////////////////////////////////////////
//  ISOUpperLayer.cs
//  Implementation of the Class ISOUpperLayer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.ICCPConfiguration;
namespace TC57CIM.IEC61970.Base.ICCPConfiguration {
	/// <summary>
	/// Is a set of configure addressing information that is required since ICCP
	/// utilizes addressing other than a TCP port.
	/// </summary>
	public class ISOUpperLayer : TCPAccessPoint {

		/// <summary>
		/// Is part of the Application Entity addressing as specified by ISO Addressing.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer aeInvoke;
		/// <summary>
		/// Is the AE qualifier and represents further application level addressing
		/// information.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer aeQual;
		/// <summary>
		/// Is a further application level OSI addressing parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer apInvoke;
		/// <summary>
		/// Is a sequence of integer strings separated by ".".  The value, in conjunction
		/// with other application addressing attributes (e.g. other APs) are used to
		/// select a specific application (e.g. the ICCP application entity) per the OSI
		/// reference model.  The sequence, and its values, represent a namespace whose
		/// values are governed by ISO/IEC 7498-3.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String apTitle;
		/// <summary>
		/// Is the addressing selector for OSI presentation addressing.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String osiPsel;
		/// <summary>
		/// Is the OSI session layer addressing information.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String osiSsel;
		/// <summary>
		/// Is the OSI Transport Layer addressing information.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String osiTsel;

		public ISOUpperLayer(){

		}

		~ISOUpperLayer(){

		}

		public override void Dispose(){

		}

	}//end ISOUpperLayer

}//end namespace ICCPConfiguration