///////////////////////////////////////////////////////////
//  PFVArControllerType1Dynamics.cs
//  Implementation of the Class PFVArControllerType1Dynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Dynamics.StandardModels;
using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
using TC57CIM.IEC61970.Dynamics.StandardInterconnections;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType1Dynamics {
	/// <summary>
	/// Power factor or VAr controller type 1 function block whose behaviour is
	/// described by reference to a standard model <font color="#0f0f0f">or by
	/// definition of a user-defined model.</font>
	/// </summary>
	public class PFVArControllerType1Dynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Excitation system model with which this power actor or VAr controller type 1
		/// model is associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics ExcitationSystemDynamics;
		/// <summary>
		/// Remote input signal used by this power factor or VAr controller type 1 model.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal RemoteInputSignal;

		public PFVArControllerType1Dynamics(){

		}

		~PFVArControllerType1Dynamics(){

		}

		public override void Dispose(){

		}

	}//end PFVArControllerType1Dynamics

}//end namespace PFVArControllerType1Dynamics