///////////////////////////////////////////////////////////
//  AggregateScore.cs
//  Implementation of the Class AggregateScore
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:55 AM
//  Original author: Gowri
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// An aggregated indicative scoring by an analytic, which is based on other
	/// analytic scores, that can be used to characterize the health of or the risk
	/// associated with one or more assets.
	/// </summary>
	public class AggregateScore : AnalyticScore {

		/// <summary>
		/// Analytic score contributing to this aggregate score.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.AnalyticScore AnalyticScore;

		public AggregateScore(){

		}

		~AggregateScore(){

		}

		public override void Dispose(){

		}

	}//end AggregateScore

}//end namespace Assets