///////////////////////////////////////////////////////////
//  AssetUser.cs
//  Implementation of the Class AssetUser
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Organisation that is a user of the asset.
	/// </summary>
	public class AssetUser : AssetOrganisationRole {

		public AssetUser(){

		}

		~AssetUser(){

		}

		public override void Dispose(){

		}

	}//end AssetUser

}//end namespace Assets