///////////////////////////////////////////////////////////
//  ComMedia.cs
//  Implementation of the Class ComMedia
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Communication media such as fibre optic cable, power-line, telephone, etc.
	/// </summary>
	public class ComMedia : Asset {

		public ComMedia(){

		}

		~ComMedia(){

		}

		public override void Dispose(){

		}

	}//end ComMedia

}//end namespace Assets