///////////////////////////////////////////////////////////
//  DiagnosisDataSet.cs
//  Implementation of the Class DiagnosisDataSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// The result of a problem (typically an asset failure) diagnosis. Contains
	/// complete information like what might be received from a lab doing forensic
	/// analysis of a failed asset.
	/// </summary>
	public class DiagnosisDataSet : ProcedureDataSet {

		/// <summary>
		/// Effect of problem.
		/// </summary>
		public string effect;
		/// <summary>
		/// Failuer mode, for example: Failure to Insulate; Failure to conduct; Failure to
		/// contain oil; Failure to provide ground plane; Other.
		/// </summary>
		public string failureMode;
		/// <summary>
		/// Cause of problem determined during diagnosis.
		/// </summary>
		public string finalCause;
		/// <summary>
		/// Code for diagnosed probem type.
		/// </summary>
		public string finalCode;
		/// <summary>
		/// Origin of problem determined during diagnosis.
		/// </summary>
		public string finalOrigin;
		/// <summary>
		/// Remarks pertaining to findings during problem diagnosis.
		/// </summary>
		public string finalRemark;
		/// <summary>
		/// Phase(s) diagnosed.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.PhaseCode phaseCode;
		/// <summary>
		/// Code for problem type determined during preliminary assessment.
		/// </summary>
		public string preliminaryCode;
		/// <summary>
		/// Date and time preliminary assessment of problem was performed.
		/// </summary>
		public System.DateTime preliminaryDateTime;
		/// <summary>
		/// Remarks pertaining to preliminary assessment of problem.
		/// </summary>
		public string preliminaryRemark;
		/// <summary>
		/// Root cause of problem determined during diagnosis.
		/// </summary>
		public string rootCause;
		/// <summary>
		/// Root origin of problem determined during diagnosis.
		/// </summary>
		public string rootOrigin;
		/// <summary>
		/// Remarks pertaining to root cause findings during problem diagnosis.
		/// </summary>
		public string rootRemark;

		public DiagnosisDataSet(){

		}

		~DiagnosisDataSet(){

		}

		public override void Dispose(){

		}

	}//end DiagnosisDataSet

}//end namespace Assets