///////////////////////////////////////////////////////////
//  DobleStandardKind.cs
//  Implementation of the Class DobleStandardKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of Doble standards.
	/// </summary>
	public enum DobleStandardKind : int {

		/// <summary>
		/// Doble test for methanol.
		/// </summary>
		methanol

	}//end DobleStandardKind

}//end namespace Assets