///////////////////////////////////////////////////////////
//  EPAStandardKind.cs
//  Implementation of the Class EPAStandardKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:07 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of EPA standards.
	/// </summary>
	public enum EPAStandardKind : int {

		/// <summary>
		/// Polychlorinated Biphenyls (PCBs) by Gas Chromatography.
		/// </summary>
		EPA8082

	}//end EPAStandardKind

}//end namespace Assets