///////////////////////////////////////////////////////////
//  FinancialInfo.cs
//  Implementation of the Class FinancialInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:11 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Various current financial properties associated with a particular asset.
	/// Historical properties may be determined by ActivityRecords associated with the
	/// asset.
	/// </summary>
	public class FinancialInfo : IdentifiedObject {

		/// <summary>
		/// The account to which this actual material item is charged.
		/// </summary>
		public string account;
		/// <summary>
		/// The actual purchase cost of this particular asset.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money actualPurchaseCost;
		/// <summary>
		/// Description of the cost.
		/// </summary>
		public string costDescription;
		/// <summary>
		/// Type of cost to which this Material Item belongs.
		/// </summary>
		public string costType;
		/// <summary>
		/// Value of asset as of 'valueDateTime'.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money financialValue;
		/// <summary>
		/// Date and time asset's financial value was put in plant for regulatory
		/// accounting purposes (e.g., for rate base calculations). This is sometime
		/// referred to as the "in-service date".
		/// </summary>
		public System.DateTime plantTransferDateTime;
		/// <summary>
		/// Date and time asset was purchased.
		/// </summary>
		public System.DateTime purchaseDateTime;
		/// <summary>
		/// Purchase order identifier.
		/// </summary>
		public string purchaseOrderNumber;
		/// <summary>
		/// The quantity of the asset if per unit length, for example conductor.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.IntegerQuantity quantity;
		/// <summary>
		/// Date and time at which the financial value was last established.
		/// </summary>
		public System.DateTime valueDateTime;
		/// <summary>
		/// Date and time warranty on asset expires.
		/// </summary>
		public System.DateTime warrantyEndDateTime;
		/// <summary>
		/// The asset to which this financial information relates.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset Asset;

		public FinancialInfo(){

		}

		~FinancialInfo(){

		}

		public override void Dispose(){

		}

	}//end FinancialInfo

}//end namespace Assets