///////////////////////////////////////////////////////////
//  LaborelecStandardEditionKind.cs
//  Implementation of the Class LaborelecStandardEditionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of editions for Laborelec standards.
	/// </summary>
	public enum LaborelecStandardEditionKind : int {

		/// <summary>
		/// No standard edition.
		/// </summary>
		none,
		/// <summary>
		/// Unknown standard edition.
		/// </summary>
		unknown

	}//end LaborelecStandardEditionKind

}//end namespace Assets