///////////////////////////////////////////////////////////
//  Medium.cs
//  Implementation of the Class Medium
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:15 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// A substance that either (1) provides the means of transmission of a force or
	/// effect, such as hydraulic fluid, or (2) is used for a surrounding or enveloping
	/// substance, such as oil in a transformer or circuit breaker.
	/// </summary>
	public class Medium : IdentifiedObject {

		/// <summary>
		/// Kind of this medium.
		/// </summary>
		public MediumKind kind;
		/// <summary>
		/// The volume of the medium specified for this application. Note that the actual
		/// volume is a type of measurement associated witht the asset.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Volume volumeSpec;
		/// <summary>
		/// Medium with which this asset is filled.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset Asset;

		public Medium(){

		}

		~Medium(){

		}

		public override void Dispose(){

		}

	}//end Medium

}//end namespace Assets