///////////////////////////////////////////////////////////
//  OperatingMechanism.cs
//  Implementation of the Class OperatingMechanism
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Breaker mechanism.
	/// </summary>
	public class OperatingMechanism : Asset {

		/// <summary>
		/// Interrupter controlled by this mechanism.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.InterrupterUnit InterrupterUnit;

		public OperatingMechanism(){

		}

		~OperatingMechanism(){

		}

		public override void Dispose(){

		}

	}//end OperatingMechanism

}//end namespace Assets