///////////////////////////////////////////////////////////
//  ProcedureKind.cs
//  Implementation of the Class ProcedureKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:21 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Kind of procedure.
	/// </summary>
	public enum ProcedureKind : int {

		/// <summary>
		/// Inspection procedure.
		/// </summary>
		inspection,
		/// <summary>
		/// Diagnosis procedure.
		/// </summary>
		diagnosis,
		/// <summary>
		/// Maintenance procedure.
		/// </summary>
		maintenance,
		/// <summary>
		/// Test procedure.
		/// </summary>
		test,
		/// <summary>
		/// Other procedure.
		/// </summary>
		other

	}//end ProcedureKind

}//end namespace Assets