///////////////////////////////////////////////////////////
//  RiskScoreKind.cs
//  Implementation of the Class RiskScoreKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:23 AM
//  Original author: Gowri
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Types of risk scores.
	/// </summary>
	public enum RiskScoreKind : int {

		/// <summary>
		/// Customer risk score.
		/// </summary>
		customerRisk,
		/// <summary>
		/// Financial risk score.
		/// </summary>
		financialRisk,
		/// <summary>
		/// Safety risk score.
		/// </summary>
		safetyRisk

	}//end RiskScoreKind

}//end namespace Assets