///////////////////////////////////////////////////////////
//  Seal.cs
//  Implementation of the Class Seal
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:23 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Physically controls access to AssetContainers.
	/// </summary>
	public class Seal : IdentifiedObject {

		/// <summary>
		/// Date and time this seal has been applied.
		/// </summary>
		public System.DateTime appliedDateTime;
		/// <summary>
		/// Condition of seal.
		/// </summary>
		public SealConditionKind condition;
		/// <summary>
		/// Kind of seal.
		/// </summary>
		public SealKind kind;
		/// <summary>
		/// (reserved word) Seal number.
		/// </summary>
		public string sealNumber;

		public Seal(){

		}

		~Seal(){

		}

		public override void Dispose(){

		}

	}//end Seal

}//end namespace Assets