///////////////////////////////////////////////////////////
//  TransformerApplicationKind.cs
//  Implementation of the Class TransformerApplicationKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:28 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Classifications of network roles in which transformers can be deployed. The
	/// classifications are intended to reflect both criticality of transformer in
	/// network operations and typical usage experienced by transformer.
	/// Note: This enumeration provides essential information to asset health analytics.
	/// The existing list is a starting point and is anticipated to be fleshed out
	/// further as requirements are better understood (PAB 2016/01/09).
	/// </summary>
	public enum TransformerApplicationKind : int {

		/// <summary>
		/// Transformer between bus at one transmission voltage level and a bus at another
		/// transmission voltage level.
		/// </summary>
		transmissionBusToBus,
		/// <summary>
		/// Transformer between bus at transmission voltage level and bus at distribution
		/// voltage level.
		/// </summary>
		transmissionBusToDistribution,
		/// <summary>
		/// Transformer is generator step-up transformer.
		/// </summary>
		generatorStepUp,
		/// <summary>
		/// Transformer between one distribution voltage level and another distribution
		/// voltage level.
		/// </summary>
		distribution

	}//end TransformerApplicationKind

}//end namespace Assets