///////////////////////////////////////////////////////////
//  UKMinistryofDefenceStandardKind.cs
//  Implementation of the Class UKMinistryofDefenceStandardKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:30 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of UK Ministry of Defence standards.
	/// </summary>
	public enum UKMinistryofDefenceStandardKind : int {

		/// <summary>
		/// Ministry of Defence, Defence Standard 05-50 (Part 65)/Issue 1 METHODS FOR
		/// TESTING FUELS, LUBRICANTS AND ASSOCIATED PRODUCTS.
		/// </summary>
		UKMOD_0550_Part65

	}//end UKMinistryofDefenceStandardKind

}//end namespace Assets