///////////////////////////////////////////////////////////
//  WEPStandardEditionKind.cs
//  Implementation of the Class WEPStandardEditionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:31 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of editions for WEP standards.
	/// </summary>
	public enum WEPStandardEditionKind : int {

		/// <summary>
		/// No edition.
		/// </summary>
		none,
		/// <summary>
		/// Unknown edition.
		/// </summary>
		unknown

	}//end WEPStandardEditionKind

}//end namespace Assets