///////////////////////////////////////////////////////////
//  TypeAssetCatalogue.cs
//  Implementation of the Class TypeAssetCatalogue
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:30 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfTypeAsset {
	/// <summary>
	/// Catalogue of generic types of assets (TypeAsset) that may be used for design
	/// purposes. It is not associated with a particular manufacturer.
	/// </summary>
	public class TypeAssetCatalogue : IdentifiedObject {

		public TC57CIM.IEC61968.Common.Status status;

		public TypeAssetCatalogue(){

		}

		~TypeAssetCatalogue(){

		}

		public override void Dispose(){

		}

	}//end TypeAssetCatalogue

}//end namespace InfTypeAsset