///////////////////////////////////////////////////////////
//  PotentialTransformer.cs
//  Implementation of the Class PotentialTransformer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:14 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.AuxiliaryEquipment;
namespace TC57CIM.IEC61970.Base.AuxiliaryEquipment {
	/// <summary>
	/// Instrument transformer (also known as Voltage Transformer) used to measure
	/// electrical qualities of the circuit that is being protected and/or monitored.
	/// Typically used as voltage transducer for the purpose of metering, protection,
	/// or sometimes auxiliary substation supply. A typical secondary voltage rating
	/// would be 120V.
	/// </summary>
	public class PotentialTransformer : Sensor {

		/// <summary>
		/// PT accuracy classification.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String accuracyClass;
		/// <summary>
		/// Nominal ratio between the primary and secondary voltage.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Float nominalRatio;
		/// <summary>
		/// Potential transformer (PT) classification covering burden.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String ptClass;
		/// <summary>
		/// Potential transformer construction type.
		/// </summary>
		public PotentialTransformerKind type;

		public PotentialTransformer(){

		}

		~PotentialTransformer(){

		}

		public override void Dispose(){

		}

	}//end PotentialTransformer

}//end namespace AuxiliaryEquipment