///////////////////////////////////////////////////////////
//  CompatibleUnit.cs
//  Implementation of the Class CompatibleUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo.Assets;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A pre-planned job model containing labor, material, and accounting requirements
	/// for standardized job planning.
	/// </summary>
	public class CompatibleUnit : WorkDocument {

		/// <summary>
		/// Estimated total cost for perfoming CU.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money estCost;
		/// <summary>
		/// The quantity, unit of measure, and multiplier at the CU level that applies to
		/// the materials.
		/// </summary>
		public string quantity;
		public TC57CIM.IEC61968.AssetInfo.Assets.CatalogAssetType GenericAssetModel;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CUGroup CUGroup;
		public TC57CIM.IEC61968.AssetInfo.Assets.Procedure Procedures;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.DesignLocationCU DesignLocationCUs;

		public CompatibleUnit(){

		}

		~CompatibleUnit(){

		}

		public override void Dispose(){

		}

	}//end CompatibleUnit

}//end namespace InfWork