///////////////////////////////////////////////////////////
//  ConditionFactorKind.cs
//  Implementation of the Class ConditionFactorKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Kind of condition factor.
	/// </summary>
	public enum ConditionFactorKind : int {

		labor,
		accountAllocation,
		material,
		travel,
		other

	}//end ConditionFactorKind

}//end namespace InfWork