///////////////////////////////////////////////////////////
//  CUAllowableAction.cs
//  Implementation of the Class CUAllowableAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Allowed actions: Install, Remove, Transfer, Abandon, etc.
	/// </summary>
	public class CUAllowableAction : WorkIdentifiedObject {

		public TC57CIM.IEC61968.Common.Status status;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CompatibleUnit CompatibleUnits;

		public CUAllowableAction(){

		}

		~CUAllowableAction(){

		}

		public override void Dispose(){

		}

	}//end CUAllowableAction

}//end namespace InfWork