///////////////////////////////////////////////////////////
//  CULaborItem.cs
//  Implementation of the Class CULaborItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.Common;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Compatible unit labor item.
	/// </summary>
	public class CULaborItem : WorkIdentifiedObject {

		/// <summary>
		/// Activity code identifies a specific and distinguishable unit of work.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String activityCode;
		/// <summary>
		/// Estimated time to perform work.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Hours laborDuration;
		/// <summary>
		/// The labor rate applied for work.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CostRate laborRate;
		public TC57CIM.IEC61968.Common.Status status;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CompatibleUnit CompatibleUnits;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.QualificationRequirement QualificationRequirements;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CULaborCode CULaborCode;

		public CULaborItem(){

		}

		~CULaborItem(){

		}

		public override void Dispose(){

		}

	}//end CULaborItem

}//end namespace InfWork