///////////////////////////////////////////////////////////
//  InfoQuestion.cs
//  Implementation of the Class InfoQuestion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Questions and answers associated with a type of document for purposes of
	/// clarification. Questions may be predefined or ad hoc.
	/// </summary>
	public class InfoQuestion : WorkDocument {

		/// <summary>
		/// Answer to question.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String answer;
		/// <summary>
		/// The date and time the quesiton was answered.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime answerDateTime;
		/// <summary>
		/// Remarks to qualify the answer.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String answerRemark;
		/// <summary>
		/// The question code. If blank, refer to questionText.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String questionCode;
		/// <summary>
		/// Remarks to qualify the question in this situation.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String questionRemark;
		/// <summary>
		/// For non-coded questions, the question is provided here.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String questionText;
		/// <summary>
		/// The type of the question.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String questionType;

		public InfoQuestion(){

		}

		~InfoQuestion(){

		}

		public override void Dispose(){

		}

	}//end InfoQuestion

}//end namespace InfWork