///////////////////////////////////////////////////////////
//  Regulation.cs
//  Implementation of the Class Regulation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Special requirements and/or regulations may pertain to certain types of assets
	/// or work. For example, fire protection and scaffolding.
	/// </summary>
	public class Regulation : WorkDocument {

		/// <summary>
		/// External reference to regulation, if applicable.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.String referenceNumber;

		public Regulation(){

		}

		~Regulation(){

		}

		public override void Dispose(){

		}

	}//end Regulation

}//end namespace InfWork