///////////////////////////////////////////////////////////
//  WorkCostSummary.cs
//  Implementation of the Class WorkCostSummary
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:32 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61968.InfIEC61968.InfWork;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A roll up by cost type for the entire cost of a work order. For example, total
	/// labor.
	/// </summary>
	public class WorkCostSummary : WorkDocument {

		public WorkCostSummary(){

		}

		~WorkCostSummary(){

		}

		public override void Dispose(){

		}

	}//end WorkCostSummary

}//end namespace InfWork