///////////////////////////////////////////////////////////
//  WorkCostDetail.cs
//  Implementation of the Class WorkCostDetail
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:32 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.InfIEC61968.InfWork;
using TC57CIM.IEC61968.InfIEC61968.InfERPSupport;
using TC57CIM.IEC61968.Work;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A collection of all of the individual cost items collected from multiple
	/// sources.
	/// </summary>
	public class WorkCostDetail : WorkDocument {

		/// <summary>
		/// Amount in designated currency for work, either a total or an individual element.
		/// As defined in the attribute "type," multiple instances are applicable to each
		/// work for: planned cost, actual cost, authorized cost, budgeted cost, forecasted
		/// cost, other.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money amount;
		/// <summary>
		/// True if 'amount' is a debit, false if it is a credit.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Boolean isDebit;
		/// <summary>
		/// Date and time that 'amount' is posted to the work.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.DateTime transactionDateTime;
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpProjectAccounting ErpProjectAccounting;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.OldWorkTask WorkTask;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.WorkCostSummary WorkCostSummary;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.ContractorItem ContractorItems;
		public TC57CIM.IEC61968.InfIEC61968.InfWork.PropertyUnit PropertyUnits;
		public TC57CIM.IEC61968.Work.Work Works;

		public WorkCostDetail(){

		}

		~WorkCostDetail(){

		}

		public override void Dispose(){

		}

	}//end WorkCostDetail

}//end namespace InfWork